### ISSUE TITLE
Collections browser support

### ISSUE THREAD

**Issue by grey93** [nzakas/understandinges6#111]
According to MDN, chrome 38+ and firefox 37+ are shipping with everything.

[Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set#Browser_compatibility)
[Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#Browser_compatibility)
[WeakMap](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap#Browser_compatibility)
[WeakSet](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet#Browser_compatibility)

Some Screenshots from chrome 41 and firefox 36 :

__Set__

![set-chrome](https://cloud.githubusercontent.com/assets/4389751/5644729/d23c4c82-968c-11e4-9726-2e0bfc5e4d3a.png)
![set-firefox](https://cloud.githubusercontent.com/assets/4389751/5644736/e131d798-968c-11e4-8530-6a65ac6a2939.png)

__Map__

![map-chrome](https://cloud.githubusercontent.com/assets/4389751/5644737/e27a5396-968c-11e4-83f6-c2c2391f7fda.png)
![map-firefox](https://cloud.githubusercontent.com/assets/4389751/5644739/e41237c8-968c-11e4-9c3b-c0cfe9db16b9.png)

__WeakMap__

![weakmap-chrome](https://cloud.githubusercontent.com/assets/4389751/5644740/e7d87106-968c-11e4-8b26-9036914a62da.png)
![weakmap-firefox](https://cloud.githubusercontent.com/assets/4389751/5644742/eafdddda-968c-11e4-8e8f-4911704a896b.png)

__WeakSet__

![weakset-chrome](https://cloud.githubusercontent.com/assets/4389751/5644745/ef2c4950-968c-11e4-9089-08641bdf39c7.png)
![weakset-firefox](https://cloud.githubusercontent.com/assets/4389751/5644746/f3048cb8-968c-11e4-956c-fc358d89c7d0.png)

**Comment by nzakas** [comment]
These aren't specific to the browser, so they are included in the `builtin` key instead. You should always merge `builtin` with whatever environment you have.

**Comment by nzakas** [comment]
Oops misread this. Thanks for the note. I'm specifically not covering browser support because it changes too much. The book is just about the language as defined by the spec.
