### ISSUE TITLE
Arrow functions, No arguments object, really?

### ISSUE THREAD

**Issue by unlight** [nzakas/understandinges6#112]
https://leanpub.com/understandinges6/read/#leanpub-auto-arrow-functions
```
No arguments object - You can’t access arguments through the arguments object,
you must use named arguments or other ES6 features such as rest arguments.
```

http://www.nczonline.net/blog/2013/09/10/understanding-ecmascript-6-arrow-functions/#comment-36639
http://mxr.mozilla.org/mozilla-central/source/js/src/jit-test/tests/arrow-functions/arguments-1.js

**Comment by nzakas** [comment]
Thanks, I'll get that fixed.

In the future, a sentence or two describing what you think the problem is would be useful.

**Comment by getify** [comment]
I believe this is inaccurate. arrow functions will have a lexical binding to the parent function's `arguments` object. In fact, arrow functions have lexical `this`, `arguments`, and `super`. So they neither have their own of those three, nor are they unable to access them. It's just that accessing them is accessing the parent's bindings.
