### ISSUE TITLE
Iterators and generators chapter: Portions of the built-in iterators section seemingly should precede the creating iterables section.

### ISSUE THREAD

**Issue by lozandier** [nzakas/understandinges6#125]
The current version of the chaptering covering iterators and generators leaves room for unnecessary confusion that can be alleviated if the collection iterators.—`entries()`, `values()`, and `keys()` are explained *before* the section on readers creating their own iteratables that depends at least on the understanding of `values()`. 

The current order of the sections does not allow that. 

Seemingly, such information about built-in iterators may be more valuable to be immediately after/between the [auto-iterables-and-for-of section](http://understandinges6.com/chap05.html#leanpub-auto-iterators-and-generators#leanpub-auto-iterables-and-for-of) that begin to explain that all of the collection objects have a default iterator.

Such a change probably would alleviate any misunderstanding of  how iterables and default iterators work before users read on  learning how to reproduce such features on their own objects.

**Comment by nzakas** [comment]
Hmmm, yeah, looks like the order of examples is a bit screwy. This is a classic chicken-and-egg problem. Iterables have to be introduced so `for-of` can be used later. You can't really explain iterables without using `@@iterator`, and the best way to explain `@@iterator` is by showing how you can define your own iterables. I'll need to ponder this a bit.

**Comment by lozandier** [comment]
Understood; I had a hunch it was a chicken-and-egg problem.

On Saturday, January 31, 2015, Nicholas C. Zakas <notifications@github.com>
wrote:

> Hmmm, yeah, looks like the order of examples is a bit screwy. This is a
> classic chicken-and-egg problem. Iterables have to be introduced so for-of
> can be used later. You can't really explain iterables without using
> @@iterator, and the best way to explain @@iterator is by showing how you
> can define your own iterables. I'll need to ponder this a bit.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nzakas/understandinges6/issues/125#issuecomment-72344760>
> .
>


-- 
Kevin Lozandier
lozandier@gmail.com <lozandier@gmail.com>

**Comment by nzakas** [comment]
Reworked this chapter. Not quite done, but should address this concern.

**Comment by lozandier** [comment]
Awesome. :)
