### ISSUE TITLE
Issues with Kindle/PDF formats distributed through leanpub

### ISSUE THREAD

**Issue by algor** [nzakas/understandinges6#131]
The very first code listing in my downloaded Kindle format starts as the following:

var text = "5536257271";
console.log(text.length);  // 2

It took me several minutes to figure out why the text that obviously consists of 10 characters should have length of 2 regardless of which edition of the JavaScript language is used.
Only when I opened PDF version I saw that the Kindle edition just plainly wrong and simply displays the codes side by side instead of the actual character.

But even using the PDF version I could not see or copy/paste the correct character. It is shown as just a rectangle (not sure how it is called in typography) - just a placeholder for a character.
I had to take the complete code provided in the next listing (134071), google for the code and then find and paste the character in Chrome console to actually check the code.

Looks like too much work for a single paragraph.

Also in the same Kindle format I have a note mark (an exclamation point in a triangle) that takes half of the page and actually hides the content of the note entirely (for example the note before "The normalize() Method"). The same is true for information notes icons "i".

Effectively, the kindle edition is not usable at the moment. Had to delete it and switch to the PDF.

**Comment by nzakas** [comment]
Sorry about that. I don't have any control over how those are rendered. I'll followup with Leanpub to see if they can look at it.
