### ISSUE TITLE
The Regular Expression y Flag

### ISSUE THREAD

**Issue by algor** [nzakas/understandinges6#132]
To me it looks like the entire section is confusing right from the start.

First paragraph says "...The y (sticky) flag indicates that the next match should be made
starting with the value of lastIndex on the regular expression."

Please compare it with the description in MDN article "..The sticky property reflects whether or not the search is sticky (searches in strings only from the index indicated by the lastIndex property".

Note the "ONLY" word in MDN? It is the crucial difference. Let me explain how the the following code and text of the section is confusing.
The code that follows: 

var pattern = /hello\d\s?/g,
text = "hello1 hello2 hello3",
result = pattern.exec(text);
console.log(result[0]); // "hello1 "
pattern.lastIndex = 7;
result = pattern.exec(text);
console.log(result[0]); // "hello2 "

Immediate question: Why do wee need to set the lastIndex property explicitly if we get *exactly* the same result with the global flag used with exec method? That is just remove the line pattern.lastIndex = 7 and you'll get the same result. 

Then follows the text: "The g flag is important as it allows the regular expression to
use lastIndex when set (without it, matches always start at 0 regardless of the lastIndex value).
The first call to exec() results in matching “hello1” first while the second call, with a lastIndex
of 7, matches “hello2” first."

Why "when set"? Again, the lastIndex is already set and takes care of itself with the global flag is used. If not then what is the usage of the global flag with exec method? It worked this way for years.

Then another paragraph that is half misleading:
"...The sticky flag tells the regular expression to save the index of the next character after the
last match in lastIndex whenever an operation is performed (in the previous example, 7 is the
location of next character after “hello1 “). If an operation results in no match then lastIndex is
set back to 0."

Again, it is *not* the intention of the sticky flag and it is not what makes it different from the  global flag.  And again, compare the definition with the MDN version and you'll see that after the half of the section a reader is still confused as to what the *real* purpose of the flag is. Just because the phrasing around "only from index" is missing from your definition.

Then  follows the code with "y" flag instead of "g". And, sorry, for the repetition, but it still can be replaced with the code above (that uses the global flag) just with the assignment of lastIndex removed and will issue the same results.

And ONLY THEN there is a paragraph:

 "....Perhaps the most important thing to understand about the sticky flag is that sticky regular
expressions have an implied ˆ at the beginning, indicating that the pattern should match from
the beginning of the input. For example, if the previous example is changed to not match the
whitespace character, there are different results:"

Questions: Why "Perhaps" word is used? What are the other *less* important things to understand? So far I did not see any differences in comparison with the global flag. 
To me the entire text of the section so far could be replaced with the corrected definition at the beginning.

Summary: it is the search *only" from the lastIndex that makes the "y" flag distinctive. That should be stated right from the start. Currently most of the text is both misleading and unnecessary.

**Comment by nzakas** [comment]
Thanks for the feedback. I disagree that the text is misleading and unnecessary, I have had other feedback from people who enjoyed this section. It sounds like you think there are some changes that could make it clearer, and I'll see what I can do about that.

**Comment by algor** [comment]
Ok, thank you. Then probably I did not manage to express myself clear. The misleading part in my opinion is that the text suggests that without "y" flag (that only preexisting  "g" flagt)  one has manually setlastIndex flag to get the same behavior. Isn't it that was implied in the whole first part of the section?If not, then, sorry, but then I can't explain why this assignment is made in the first listing.
And the main point of the "g" flag is covered only at the very and of the section. Probably I can't explain myself clearer then that ). If I got it all wrong, then sorry once again.

**Comment by nzakas** [comment]
From @getify:

The example given for the `/y` sticky flag is:

```js
var pattern = /hello\d\s?/y,
    text = "hello1 hello2 hello3",
    result = pattern.exec(text);

console.log(result[0]);             // "hello1 "
console.log(pattern.lastIndex);     // 7

result = pattern.exec(text);

console.log(result[0]);             // "hello2 "
console.log(pattern.lastIndex);     // 14
```

This example is given to suggest that it's a benefit over the `g` global flag mode, in that `lastIndex` is automatically updated on each match. But to my understanding, `g` global mode **also** automatically updates `lastIndex` when using `exec(..)`.

To illustrate my point, here's the same example but using `g` instead of `y`, and it seems to behave identically to your `y` example (tested in Chrome and FF):

```js
var pattern = /hello\d\s?/g,
    text = "hello1 hello2 hello3",
    result = pattern.exec(text);

console.log(result[0]);             // "hello1 "
console.log(pattern.lastIndex);     // 7

result = pattern.exec(text);

console.log(result[0]);             // "hello2 "
console.log(pattern.lastIndex);     // 14
```

So it's not clear from your text what the benefit of `y` is in this respect?

------

I'm not sure about this at all, but I thought that sticky mode's benefit was that this stickiness (updating and respecting `lastIndex`) was possible with other utilities besides `exec(..)`.

Am I missing something?

**Comment by nzakas** [comment]
I spent a long time trying to figure out the benefit of the sticky flag, so I'll have to go dig up my notes as I can't quite remember how I internalized it. (And whether I internalized it correctly or not is a whole other story.) I'll definitely take a look.

**Comment by getify** [comment]
I'm not entirely positive that I'm 100% accurate here, but this is my understanding of the sticky flag:

https://github.com/getify/You-Dont-Know-JS/blob/master/es6%20&%20beyond/ch2.md#sticky-flag

Someone [has already questioned](https://twitter.com/ziyunfei/status/571112542182846464) the next to last paragraph of that section, where I assert that sticky changes `^` behavior. Perhaps that was going to be true of `y` and isn't anymore. Still trying to figure it out.

As you sift through your bits of info, I'd sure appreciate any comments here so I can vet that against my own writings. Hoping we can get to the bottom of all this quickly. :)

**Comment by nzakas** [comment]
At the moment, this is the most concise note I've found:

> the most important thing to understand about the sticky flag is that sticky regular expressions have an implied `^` at the beginning.

Could it really be that simple? I'll dig in more when I have more energy.

**Comment by getify** [comment]
> the most important thing to understand about the sticky flag is that sticky regular expressions have an implied ^ at the beginning.

Not to be too contrarian, and I'm certainly not very confident, but I think I'm (in my explorations of the spec) coming to the opposite conclusion -- that is, that an expression with a `^` anchor cannot match more than its first time, even with a sticky mode on it.

Imagine this:

```js
var re = /^b../y,
    str = "bam book black";

re.exec( str );   // ["bam"]
re.lastIndex;    // 3
re.exec( str) ;   // ????
```

Does it really make sense that `y` makes `^` relative to `lastIndex`, such that `????` should be `["boo"]`? I've tried to find that in the ES6 spec, and I don't see it.

**Comment by getify** [comment]
Update:

https://github.com/v8/v8/blob/master/test/mjsunit/harmony/regexp-sticky.js#L121

That is, I think the `????` in my previous example would have to be `null`, because of the `^` in the pattern. At least if that comment in v8's test suite is accurately understanding the spec.

**Comment by nzakas** [comment]
Okay, the sticky flag is really two things:

1. There is an implicit `^` at the beginning. 
2. The `^` refers to the substring beginning at `lastIndex`.

Your example doesn't work because when `lastIndex` is 3, it's referring to the space between "bam" and "book". If you change it, this is what you get:

```js
var re = /^b../y,
    str = "bam book black";

re.exec( str );   // ["bam"]
re.lastIndex;     // 3
re.lastIndex = 4;
re.exec( str ) ;   // boo
```

**Comment by getify** [comment]
Unfortunately, I think the spec contradicts your assertions. Sorry to be a PITA, but trying really hard to get this straight.

From [21.2.2.6](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-assertion):

> Note: Even when the y flag is used with a pattern, ^ always matches only at the beginning of Input, or (if Multiline is true) at the beginning of a line.

**Comment by nzakas** [comment]
You're not being a PITA, I want to figure it out. :) It looks like Firefox has a bug, then (from Scratchpad):

```js
var re = /^o/y;

re.lastIndex = 4;
re.test("Hello world");

/*
true
*/
```

If `^` was meant to always match the start of input, then this should be false.

**Comment by getify** [comment]
> It looks like Firefox has a bug

I don't think Firefox has a bug. The problem is FF invented `y` years ago, with the behavior you're observing of `y` being relative to `lastIndex`, but the ES6 spec diverged from that, and FF has not yet updated. :/

**Comment by nzakas** [comment]
Well, Firefox didn't have a bug until `y` was added to ES6, and NOW it has a bug. :) Yay standardizing implemented things.

Okay, back to the drawing board.

**Comment by getify** [comment]
OK, here's what I've got currently as a synopsis... still rough though:

> 1. y can (partially) be emulated with g + exec(..), but the use of the g flag changes other regex-aware utilities (like String#match(..)) in perhaps-unwanted ways (match(/../g) grabs all matches all at once, instead of one-at-a-time), whereas match(/../y) will give you the sticky like benefits (lastIndex) without changing the one-at-a-time behavior of match(..).
> 2. y can be seen as to restrain a behavior that's not possible to restrain with g + exec(..), which is that g + exec(..) will automatically "look forward" in the input string from wherever lastIndex currently is, perhaps finding it past lastIndex. y says "no, no, you can only find this at exactly lastIndex, or not at all".

**Comment by nzakas** [comment]
Nice! I think that's correct. I was actually going to post this before I saw your response:

> I think the key thing is that `y` has no forward references, so the match must be at exactly `lastIndex` to be found. The explicit inclusion of `^` would therefore effectively make `lastIndex = 0`.

**Comment by getify** [comment]
> The explicit inclusion of ^ would therefore effectively make lastIndex = 0.

I don't think this part is quite correct. I think if you have `/^b../y` and you set `lastIndex` to something `> 0`, I think the match will just automatically fail. In other words, `y` + `lastIndex > 0` + `^` in an incompatible combination.

**Comment by getify** [comment]
FWIW, I've completely rewritten (and expanded) my book section on "sticky mode" after all these explorations. If it helps at all, here how I went about it:

https://github.com/getify/You-Dont-Know-JS/blob/master/es6%20&%20beyond/ch2.md#sticky-flag

**Comment by nzakas** [comment]
> I don't think this part is quite correct. I think if you have /^b../y and you set lastIndex to something > 0, I think the match will just automatically fail. In other words, y + lastIndex > 0 + ^ in an incompatible combination.

Looking at this again, I'm not sure this description is correct. If you have both `y` and `m`, `lastIndex` must continue to be greater than 0 in order for the multiline behavior to work correctly. This is what happens with `g`:

```js
var re = /^foo/gm;
re.test("foo\nfoo");
console.log(re.lastIndex);   // 3
re.test("foo\nfoo");
console.log(re.lastIndex);   // 7
```

I'd expect the `y` flag to have to act similarly in order to get a similar result.

**Comment by nzakas** [comment]
Also, updated the section to be more clear.

@getify You can feel free to remove the "other literature" remark now :-P

**Comment by getify** [comment]
@nzakas your's was definitely not the only one that "other literature" was referring to. MDN (IIRC) says it, as have several blog posts and SO answers. ;-)
