### ISSUE TITLE
Wording in Symbols::Sharing Symbols

### ISSUE THREAD

**Issue by jakub-g** [nzakas/understandinges6#135]
https://github.com/nzakas/understandinges6/blob/master/manuscript/04-Symbols.md#sharing-symbols

I found the wording of the following sentence confusing:

> The Symbol.for() method accepts a single parameter, which is a string identifier for the symbol you want to create **(this value doubles as the description)**

maybe it could be somehow reworded?

**Comment by nzakas** [comment]
Can you explain what you found confusing?

**Comment by jakub-g** [comment]
If I understand correctly you used "double" with the meaning as in "a test double" (a replacement) but it took me many readings through the sentence to figure it out (I was thinking about doubling as "duplicating" and I was wondering what is duplicated and why). Probably for native speakers this is less ambiguous :) Feel free to decide if it's worth doing sth with this.

**Comment by nzakas** [comment]
Ah ok, maybe a bit too colloquial wording, I'll try to clear that up.
