### ISSUE TITLE
03-Objects: Expand the explanation of "toMethod()"

### ISSUE THREAD

**Issue by jakub-g** [nzakas/understandinges6#139]
https://github.com/nzakas/understandinges6/blob/master/manuscript/03-Objects.md#summary

> You can change how super is evaluated inside of a function by calling toMethod() and specifying a new [[HomeObject]]. This method returns a new copy of the function whose [[HomeObject]] is the argument that was passed in.

Contrary to everything else in the summary, the information about `toMethod()` is nowhere written in the main part of the chapter, *just as the last sentence of the summary.*

I think this deserves to be *at least in a separate paragraph* and perhaps accompanied with a code snippet for better clarity (maybe even moved from summary to an earlier chapter). For completeness I would also reference `Function.prototype.bind()` when writing about `toMethod()` since it's pretty similar but changes `this`-binding (even though it's not new in ES6) - to hint the reader about the similarity.

Regards,
Jakub

**Comment by nzakas** [comment]
That's a mistake. `toMethod` was removed from the spec so I removed it from the book. I just forgot the summary.
