### ISSUE TITLE
Sticky Flag example is confusingly illustrated

### ISSUE THREAD

**Issue by getify** [nzakas/understandinges6#142]
The example given for the `/y` sticky flag is:

```js
var pattern = /hello\d\s?/y,
    text = "hello1 hello2 hello3",
    result = pattern.exec(text);

console.log(result[0]);             // "hello1 "
console.log(pattern.lastIndex);     // 7

result = pattern.exec(text);

console.log(result[0]);             // "hello2 "
console.log(pattern.lastIndex);     // 14
```

This example is given to suggest that it's a benefit over the `g` global flag mode, in that `lastIndex` is automatically updated on each match. But to my understanding, `g` global mode **also** automatically updates `lastIndex` when using `exec(..)`.

To illustrate my point, here's the same example but using `g` instead of `y`, and it seems to behave identically to your `y` example (tested in Chrome and FF):

```js
var pattern = /hello\d\s?/g,
    text = "hello1 hello2 hello3",
    result = pattern.exec(text);

console.log(result[0]);             // "hello1 "
console.log(pattern.lastIndex);     // 7

result = pattern.exec(text);

console.log(result[0]);             // "hello2 "
console.log(pattern.lastIndex);     // 14
```

So it's not clear from your text what the benefit of `y` is in this respect?

------

I'm not sure about this at all, but I thought that sticky mode's benefit was that this stickiness (updating and respecting `lastIndex`) was possible with other utilities besides `exec(..)`.

Am I missing something?

**Comment by nzakas** [comment]
I think you're reporting the same thing as #132. So I'm going to consolidate on that.
