### ISSUE TITLE
ch4 Symbols: instanceof Symbol

### ISSUE THREAD

**Issue by getify** [nzakas/understandinges6#144]
> It's not possible to create an instance of Symbol

Actually, you can, indirectly:

```js
var s = Symbol();
s instanceof Symbol;  // false

var sym = Object(s);
sym instanceof Symbol;  // true
```

**Comment by nzakas** [comment]
Thanks, I'll probably just change the wording rather than delving into this strange case.

**Comment by getify** [comment]
FYI: both the symbol primitive and the boxed Symbol object form of the value are interchangeable in all places. The object form lets you add other properties to it. It's quite possible people may end up using the object form of symbols in those cases.

**Comment by nzakas** [comment]
Good to know.
