### ISSUE TITLE
rest parameter vs spread operator

### ISSUE THREAD

**Issue by Mouvedia** [nzakas/understandinges6#145]
You should better explain their differences. Something about the fact that one is used for function expression/declaration and the other for function invocations. Also these chapters shouldn't be separated by Destructured Parameters.

**Comment by getify** [comment]
@Mouvedia note: that's not the correct distinction... the `...` operator can be used in a "spread" or in a "gather" context, it has little to do with functions themselves.

For example:

```js
var [a,b, ...others] = [1,2,3,4,5];    // in an assignment/declaration context, `...` is "gather"
a; // 1
b; // 2
others; // [3,4,5]

var x = [ ...others, a, b ];   // in an expressino/value context, `...` is "spread"
x; // [3,4,5,1,2]
```

**Comment by Mouvedia** [comment]
Yeah that's a good example too. I mean there is a value in putting these "gather" vs "spread" examples next to each other. Suddenly you assimilate one notion not two.

**Comment by nzakas** [comment]
Reworked a lot of this content. I think the distinction is clear now.
