### ISSUE TITLE
Superscripts aren't showing properly on leanpub

### ISSUE THREAD

**Issue by danzimm** [nzakas/understandinges6#147]
The example I saw is in the section `Safe Integers`. The second sentence states

> JavaScript can only accurately represent integers between -253 and 253

When it should be something like `-2^53 - 2^53`. I see in the MD file the proper `2^53^` are there, but it appears this is an issue with leanpub. I inspected the page and it even has the `<sup>` tags but I'm guessing some CSS is overriding it? By no means am I a web guru so I can't really find the issue. Anyhow this was tested in Google Chrome 41.0.2272.89 on OS X and Safari 8.0.5, again on OS X (the safari is a beta build and I've been having some weird rendering issues so I'd ignore anything failing in there for now).

**Comment by nzakas** [comment]
Ah weird, I'll look into it and contact them.

**Comment by nzakas** [comment]
Reported to Leanpub and they are looking into it. Will leave this open to remind myself to followup.

**Comment by nzakas** [comment]
This has been fixed.
