### ISSUE TITLE
Implement AnchorJS

### ISSUE THREAD

**Issue by montogeek** [nzakas/understandinges6#149]
It is possible to implement https://github.com/bryanbraun/anchorjs on the project, it would be nice to share a link quickly about this great book :)

**Comment by nzakas** [comment]
I'm not sure what you're asking. Can you explain what you're trying to do?

**Comment by montogeek** [comment]
I want to share a section of the page using HTML Anchors, ie https://leanpub.com/understandinges6/read/#leanpub-auto-better-unicode-support, the plugins just make it easier to share

**Comment by nzakas** [comment]
I have no control over Leanpub.
