### ISSUE TITLE
Slight misleading around `super`

### ISSUE THREAD

**Issue by getify** [nzakas/understandinges6#150]
> At it's simplest, super acts as a pointer to the current object's prototype, effectively acting like `Object.getPrototypeOf(this)`

> The call to `super.getGreeting()` is the same as `Object.getPrototypeOf(this).getGreeting.call(this)`

It's slightly misleading to suggest that `super` == `Object.getPrototypeOf(this)`. That's **only** true in a method at the bottom of the chain, which your example happens to show, but which most uses will not match (and thus `Object.getPrototypeOf(this)` would not work as a stand-in!)

**TL;DR**: I'd recommend adding a warning/note that `Object.getPrototypeOf(this)` is not as safe as `super`, because if the method it's used in is not at the bottom of the chain, it all breaks hard.

------

To illustrate:

```js
var o1 = {
   id: "o1",
   foo: function() { console.log(this.id); }
};

var o2 = {
   id: "o2",
   foo: function() {
      Object.getPrototypeOf(this).foo.call(this);  // instead of `super.foo()`
   }
};

Object.setPrototypeOf(o2,o1);

o2.foo(); // o2
```

That happens to work fine. But, if you then do:

```js
var o3 = Object.create(o2);
o3.foo();
```

Now, `foo()` is not at the bottom of the chain. `o3` is. The `Object.getPrototypeOf(this).foo.call(this)` results in infinite recursion, because `Object.getPrototypeOf(o3)` is `o2`, so `o2.foo.call(o3)` reinvokes it with `o3` again, and that cycle repeats forever.

`super.foo()` would not suffer recursion here, since it's relative to where `foo()` is found, not to the `this` binding.

In fact, this observation is basically the only reason `super` even exists in ES6.

**Comment by lozandier** [comment]
Great further explanation of the importance of `super` in ES6, @getify!
