### ISSUE TITLE
`super()` not allowed in derived methods

### ISSUE THREAD

**Issue by getify** [nzakas/understandinges6#151]
> If you're calling a prototype method with the exact same name, then you can also call super as a function

This is no longer true. It was removed from ES6 a few months ago. You have to do `super.foo()` in a derived class method, not just `super()`.

**Comment by nzakas** [comment]
Yup, just haven't had time/energy to go back and update. Hopefully soon.

**Comment by getify** [comment]
No rush. Just making sure it was documented. :)

**Comment by nzakas** [comment]
Much appreciated. I was just commenting to let you know I had read it. :)
