### ISSUE TITLE
`super.XXX` can only be used in concise methods

### ISSUE THREAD

**Issue by getify** [nzakas/understandinges6#152]
> W> super references can only be used inside of functions and cannot be used in the global scope. Attempting to use super in the global scope results in a syntax error.

Recommend you tweak this note/warning from "functions" to indicate that `super` (as `super.XXX` or `super.YYY()`) can only be used in concise methods, not normal function expression properties:

```js
var o = {
   __proto__: parent,
   foo() { super.foo(); }, // allowed
   bar: function() { super.bar(); }  // not allowed
};
```

**Comment by nzakas** [comment]
Yup, it's been on my todo list

**Comment by getify** [comment]
No rush. Just making sure it was documented. :)
