### ISSUE TITLE
Chapter 3: Typo in Object.assign() section?

### ISSUE THREAD

**Issue by JeremyCaney** [nzakas/understandinges6#153]
In Chapter 3, in the section on `Object.assign()`, you make the following statement:

> Since the **`mixin()`** method uses the assignment operator (`=`), it cannot copy accessor properties to the receiver as accessor properties

I believe this should read:

> Since the **`assign()`** method uses the assignment operator (`=`), it cannot copy accessor properties to the receiver as accessor properties

The (later removed) `mixin()` method *did* support accessor properties, as discussed in the next paragraph:

> The primary difference was that Object.mixin() also copied over accessor properties, but the method was removed due to concerns over the use of super (discussed later in this chapter).

**Comment by nzakas** [comment]
In this case `mixin()` is referring to the function of the same name in the immediate preceding example.

**Comment by JeremyCaney** [comment]
Aha, I had a feeling I might be confused here. 

The reason I was getting tripped up was around the statement "The name `Object.assign()` was chosen to reflect this distinction", which I took to suggest that `Object.assign()` operates differently than `mixin()`. I.e., that `mixin()` uses assignment, but `Object.assign()` does not, thus the need to distinguish them. That is obviously contracted by the later note "Working with Accessor Properties". 

Based on re-reading this section, I believe the intent is to note that the popular identifier `mixin()` is actually unclear because it might suggest that accessor properties are maintained (even though they are not). As such, to mitigate this ambiguity, ECMAScript uses `Object.assign()` to be more explicit about the functionality. Yes?

It *may* be worth rewording this for clarity. That said, it's also worth noting that I'm under the weather today and so the confusion may entirely be on my end; indeed, I didn't find this confusing the first time I read this.

**Comment by JeremyCaney** [comment]
After re-reading this (again), I think it's fine as is. In context it is clear, especially since you state "which behaves the same way". Apologies for the false alarm / distraction!
