### ISSUE TITLE
Function names examples do not work using babel

### ISSUE THREAD

**Issue by abdulapopoola** [nzakas/understandinges6#155]
The function names when evaluated with babel do not all return values.

```js
console.log(person.firstName.name); // "get firstName"
```

This returns undefined while the second example with bound function names is empty too.

```js
var doSomething = function() {};
console.log(doSomething.bind().name); //empty
console.log((new Function()).name);    //empty
```

Am I getting my compilation wrong in some way?

**Comment by nzakas** [comment]
I'm not familiar with all of the Babel options, but it looks like it hasn't implemented function names.

**Comment by getify** [comment]
Not all function name inferences will be transpilable. Known limitations with babel.
