### ISSUE TITLE
IIFEs

### ISSUE THREAD

**Issue by davidgilbertson** [nzakas/understandinges6#165]
In the example for IIFEs using an anonymous function, you have this:
````
let person = (function(name) {

    return {
        getName() {
            return name;
        }
    };

}("Nicholas"));

console.log(person.getName()); 
````
And point out that the position of the parentheses when doing the same with an arrow function is different.
I might be wrong, but in the example, aren't the parentheses superfluous (only there to provide clarity?)
i.e. these two work just fine:
````
let person = (function(name) {

    return {
        getName() {
            return name;
        }
    };

})("Nicholas");

console.log(person.getName()); 
````
or
````
let person = function(name) {

    return {
        getName() {
            return name;
        }
    };

}("Nicholas");

console.log(person.getName()); 
````

Great book by the way!

**Comment by nzakas** [comment]
Yeah, in the case of an assignment, they are superfluous. I probably need to change that example to not use assignment.
