### ISSUE TITLE
Legacy multiline string examples are misleadingly different than the template string example

### ISSUE THREAD

**Issue by lostnet** [nzakas/understandinges6#166]
Cause for confusion?
=================

In the section on multiline strings, the first two examples are spanning **a single line string** across multiple lines of source code for developer readability, while the template string example is embedding the \n to create **a real multiline string**.

For example: 

     let message = [
    "Multiline ",
    "string"
    ].join("");

needs to be:

    let message = [
    "Multiline ",
    "string"
    ].join("\n");

    let message = "Multiline \n" +
        "string";

to be equivalent to:

    let message = `Multiline
    string`;

Suggested fix?
==========
Since the equivalent first example would look pretty ugly (and uncommon in web programming):

    let message = "Multiline \n\
    string";

I think it would be necessary to start with the current first example then segway to the possibility of wanting to include the newline before showing the second set of legacy solutions corrected to be  equivalent to the template string?

**Comment by nzakas** [comment]
Thanks, I'll take a look.
