### ISSUE TITLE
About the promise chain is broken by rejection handler without return a value.

### ISSUE THREAD

**Issue by Summerlve** [nzakas/understandinges6#171]
I test the next code in chrome and nodejs:
```javascript
"use strict";
var p1 = new Promise(function(resolve, reject) {
    reject(42);
});

p1
	.catch(
		function (value) {
	    	console.log(value);         
			throw new Error("test");
		}
	)
	.then(
		function (value) {
	    	console.log(value);       
		},
		function (error) {
			console.log(error.message);	
		}
	);
```

and the result is:
42
test

the result showed that rejection handler doesn't broke the promise chain.

**Comment by Summerlve** [comment]
at the end of  chapter 10, zakas said rejection handler will broke the chain without return a value.

**Comment by nzakas** [comment]
The rejection handler is throwing an error, that's why the chain isn't broken.

**Comment by Summerlve** [comment]
but I also test the following code:

```javascript"use strict";

let p1 = new Promise(function(resolve, reject) {
    reject(42);
});

p1.catch(function(value) {
    console.log(value);         // "42"
}).then(function(value) {
    console.log(value);         // undefinded
});
```
and the result is:
42
undefinded

**Comment by Summerlve** [comment]
My understanding is: the .then() and .catch() will return a next promise resolved if no throwing error in fulfillment handler or rejection handler, if which one either handler throwing an error  then .then() and .catch() will return a promise rejected.

**Comment by Summerlve** [comment]
And just like call the resolve() or reject(), the previous promise will pass argument into next promise.
