### ISSUE TITLE
Suggestion for 11-Modules section

### ISSUE THREAD

**Issue by tiagorg** [nzakas/understandinges6#173]
The example for the section **Importing Without Bindings** is very effective and passes the message really well, however I think it is a little bit dangerous because it is augmenting a global function, in a non-idempotent way, so every time this module is required, it will re-set again.

So I would like to suggest adding an if condition before it:

```javascript
// module code without exports or imports
if (typeof Array.prototype.pushAll === "undefined") {
    Array.prototype.pushAll = function(items) {

        // items must be an array
        if (!Array.isArray(items)) {
            throw new TypeError("Argument must be an array.");
        }

        // use built-in push() and spread operator
        return this.push(...items);
    };
}
```

It might also be good to remark that developing new objects/functions this way is not a best practice, so it should be avoided as much as possible because this will necessarily deal with the Global scope.

If you guys like the idea I can submit a PR

**Comment by getify** [comment]
From the ES6 module perspective, modules are singletons, so the module's code (that is, the stuff above) is only ever running once per program, even if it's `import`ed many times.

**Comment by tiagorg** [comment]
Gotcha. Thanks for the clarification, Kyle. If I may suggest perhaps this explanation could be given on the text, that modules are singletons. I am afraid more people might have the same question

**Comment by nzakas** [comment]
Yup, good suggestion. I'll make that addition.

**Comment by tiagorg** [comment]
Sweet!
