### ISSUE TITLE
Defensive Objects using Proxies

### ISSUE THREAD

**Issue by scottsilvi** [nzakas/understandinges6#180]
Hey dude - not sure where else to put this. Your blog post on this has closed comments. I also know your chapter on Proxies is still very much in flight, but wanted to open up some dialog.

First of all, the amount of thanks with which I should supply you is somewhere less than the amount of thanks you'll undoubtedly receive. That is to say, I cannot thank you enough... in a roundabout way. Why am I still typing?

Started kicking the tires on defensive objects, paired with type safety, to create an aptly named `typeSafeDefensiveProxy` proxy. 

Given this (from your example): 

    function createDefensiveObject(target) {

        return new Proxy(target, {
            get: function(target, property) {
                if (property in target) {
                    return target[property];
                } else {
                    throw new ReferenceError("Property \"" + property + "\" does not exist.");
                }
            }
        });
    }
    let person = {
        name: "Nicholas"
    };

    let defensivePerson = createDefensiveObject(person);

    console.log(defensivePerson.name);      // "Nicholas" 
    console.log(defensivePerson.age);       // ReferenceError!

Were you to execute something like: 

    JSON.stringify(defensivePerson)

JSON.stringify will first attempt to call a `toJson` method on `defensivePerson`, per the [JSON source](https://github.com/douglascrockford/JSON-js/blob/master/json2.js#L250): 

        if (value && typeof value === 'object' &&
                typeof value.toJSON === 'function') {
            value = value.toJSON(key);
        }

As a result, the `defensivePerson` object will throw the `ReferenceError`. 

Incidentally, I was using [BlueBird](https://github.com/petkaantonov/bluebird) to fetch data, and upon resolution, new up a model instance which was using this proxy. `BlueBird` was actually attempting to call `obj.then` at one point, so I actually receive two reference errors, simply by implementing a defensive object. 

How might one implement a proxy that is more of a `moderatelyDefensiveObject`?

**Comment by nzakas** [comment]
I'm sorry, I don't have the time to dig into this as it's not related to the book. I'd suggest posting something on StackOverflow.

**Comment by scottsilvi** [comment]
Hey dude - yeah I'm not necessarily asking for you to solve this in the immediate, or I'd go to SO.

I merely wanted to provide an example of defensive objects in a real-world implementation describing the liberal use of property accessors among ubiquitous libraries (such as Bluebird or JSON2). I know Ch 13 is a WIP - and I know there are dozens of awesome use cases for proxies - but if defensive objects are going to be a cornerstone of this chapter, I feel it merits mentioning that you're going to introduce myriad Reference Errors for any libs that may try and access your objects for legitimate reasons.

**Comment by nzakas** [comment]
As far as I know, only Edge has fully implemented proxies, so trying to use them anywhere else means you'll be using a buggy implementation that might actually work in the future. Firefox, in particular, has several open bugs related to proxies and my examples don't work there. 

Bottom line: unless you're using Edge, it's hard to know if there's a problem or not. 

Once I get to this chapter, I'll do some exploration to see what should be happening in various scenarios.
