### ISSUE TITLE
Duplicate Object Literal Properties - ES6

### ISSUE THREAD

**Issue by abz123** [nzakas/understandinges6#182]
Suppose to get 2nd value displayed from duplicate name but dont. 
On latest google chrome/linux mint:

Error:
Duplicate data property in object literal not allowed in strict mode
You may need an appropriate loader to handle this file type.
var person = {
  name: "Nicholas",
  name: "Greg"
};
console.log(person.name);

**Comment by nzakas** [comment]
This doesn't appear to be related to the book, so closing.

**Comment by ab2qik** [comment]
I bought your book on leanpub and its from page 72 with title = Duplicate Object Literal Properties.

**Comment by nzakas** [comment]
Can you be more specific about what you're reporting? I can't tell if you're saying the book is wrong, or the browser is wrong, or something else.

**Comment by ab2qik** [comment]
I am just reporting the error seen with the code when viewed on
Linux/chrome. I dont know if it works on another setup. If it does work on
another one then it could be a bug on linux/chrome?

Could you please confirm that?

I think your book coverage is clear, thorough and well explained.


On Mon, Oct 19, 2015 at 7:20 PM, Nicholas C. Zakas <notifications@github.com

**Comment by nzakas** [comment]
I'm sorry, I can't tell what it is you're reporting. You haven't given me enough details to be able to respond. It would be helpful if you could describe:

1. What you did.
2. What you expected to happen.
3. What actually happened.

**Comment by weakish** [comment]
This is because the browser is using ES5.

The current version of the book mentioned this.
