### ISSUE TITLE
Creating Unsettled Promises

### ISSUE THREAD

**Issue by tickleux** [nzakas/understandinges6#184]
```javascript
let promise = new Promise(function(resolve, reject) {
    console.log("Promise");
    resolve();
});
console.log("Hi!");
```
The output of the above code should be:
```
Promise
Hi!
```

**Comment by nzakas** [comment]
Are you reporting a problem in the book?

**Comment by tickleux** [comment]
yes. https://leanpub.com/understandinges6/read#leanpub-auto-promises

**Comment by nzakas** [comment]
What's the problem? Which section?

**Comment by tickleux** [comment]
Promises -> Promise Basics -> Creating Unsettled Promises

![](http://i.imgur.com/tfCE2tl.png?1)

I tried the example, and my output is:

```
Promise
Hi !
```

**Comment by nzakas** [comment]
Ah, I see. Hmm, that's very strange. I thought the executor isn't supposed to be executed right away, I'll have to dig into that detail.

**Comment by getify** [comment]
The executor definitely executes synchronously right away. Resolution events are async.

**Comment by nzakas** [comment]
Thanks @getify!
