### ISSUE TITLE
Destructuring Assignment with Object Properties

### ISSUE THREAD

**Issue by yangsu** [nzakas/understandinges6#200]
In the [Destructuring Assignment section of Chapter 5](https://github.com/nzakas/understandinges6/blob/master/manuscript/05-Destructuring.md#destructuring-assignment), you mentioned it's possible to store values into object properties. Specifically this example,

```javascript
let node = {
        type: "Identifier",
        name: "foo"
    },
    anotherNode = {};

({ anotherNode.type, anotherNode.name } = node);

console.log(anotherNode.type);  // "Identifier"
console.log(anotherNode.name);  // "foo"
```

I've tried this in the Node (5.1) console, as well as [babel repl](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=let%20node%20%3D%20%7B%0A%20%20%20%20%20%20%20%20type%3A%20%22Identifier%22%2C%0A%20%20%20%20%20%20%20%20name%3A%20%22foo%22%0A%20%20%20%20%7D%2C%0A%20%20%20%20anotherNode%20%3D%20%7B%7D%3B%0A%0A(%7B%20anotherNode.type%2C%20anotherNode.name%20%7D%20%3D%20node)%3B%0A%0Aconsole.log(anotherNode.type)%3B%20%20%2F%2F%20%22Identifier%22%0Aconsole.log(anotherNode.name)%3B%20%20%2F%2F%20%22foo%22%0A), both show syntax errors.

```
repl: Unexpected token (7:14)
   5 |     anotherNode = {};
   6 | 
>  7 | ({ anotherNode.type, anotherNode.name } = node);
     |               ^
   8 | 
   9 | console.log(anotherNode.type);  // "Identifier"
  10 | console.log(anotherNode.name);  // "foo"
```

I've also looked at the [destructuring spec](http://wiki.ecmascript.org/doku.php?id=harmony:destructuring), and there are no examples of the feature you mentioned above. Do you mind elaborating?

Thanks in advance!

**Comment by nzakas** [comment]
I'll have to double check the spec (I'd suggest not relying on the strawman as it's quite old and may not be up to date).

**Comment by nzakas** [comment]
Confirmed, the text is incorrect. I'll get that fixed.
