### ISSUE TITLE
for-of loop Map destructuring

### ISSUE THREAD

**Issue by ronen-e** [nzakas/understandinges6#204]
It might be a nice addition to add an example of Map for-of  destructuring in either the chapter about Maps or the chapter about Generators. 

```js
let map = new Map();
map.set( "month", "January" );
map.set( "year", "2016" );

for (let [key, value] of map) {
    console.log(`${key} = ${value}`);
}

// outputs: 
// month = January
// year = 2016
```

**Comment by nzakas** [comment]
Good suggestion, I'll see if I can add that before my deadline.
