### ISSUE TITLE
Object.keys() and Reflect.enumerate() do not have a specific order

### ISSUE THREAD

**Issue by nzakas** [nzakas/understandinges6#206]
In the section "Own Property Enumeration Order" in Chapter 4:

> This affects how properties are returned using a `for-in` loop, `Object.keys()`, `Object.getOwnPropertyNames()`, and `Reflect.ownKeys` (covered in chapter 12). It also affects the order in which properties are processed by `Object.assign()` and `JSON.stringify()`.

This is incorrect, `for-in` and `Object.keys()` do not have a set order other than being the same in any implementation.

References:

> If an implementation defines a specific order of enumeration for the for-in statement, the same order must be used for the elements of the array returned in step 4.

Source: http://www.ecma-international.org/ecma-262/6.0/#sec-object.keys

> Historically, the for-in order was not defined and there has been variation among browser implementations in the order they produce.(and other specifics). ES5 added Object.keys and the requirement that it should order the keys identically to for-in. During development of both ES5 and ES6 the possibility of defining a defining a specific for-in order was considered but not adopted because of web legacy compatibility concerns and uncertainly about the willingness of browsers to make changes in the ordering they currently produce.

Source: https://esdiscuss.org/topic/property-ordering-of-enumerate-getownpropertynames

**Comment by raulsebastianmihaila** [comment]
The same goes for JSON.stringify, which uses EnumerableOwnNames (which orders the keys the same as for-in).

http://www.ecma-international.org/ecma-262/6.0/#sec-serializejsonobject  
http://www.ecma-international.org/ecma-262/6.0/#sec-enumerableownnames

**Comment by nzakas** [comment]
Thanks @raulsebastianmihaila
