### ISSUE TITLE
Mention that `Array.from` accepts Sets

### ISSUE THREAD

**Issue by robinpokorny** [nzakas/understandinges6#208]
In the ‘Converting to an Array’ section of the ‘Sets in ECMAScript 6’ subchapter of the ‘Chapter 7: Sets and Maps’ the spread operator is recommended. I would suggest to explicitly mention one can also use `Array.from` method (covered in ‘Chapter 10: Arrays’).

Additionally I feel that converting a set to an array is not a good use case for the spread operator at all. [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator) reads: ‘The spread operator allows an expression to be expanded in places where multiple arguments (for function calls) or multiple elements (for array literals) are expected.’ Which does not to be the case here.

**Comment by nzakas** [comment]
Array.from isn't introduced until later, so I don't want to use it in that chapter.
