### ISSUE TITLE
Iterate over object properties example

### ISSUE THREAD

**Issue by ronen-e** [nzakas/understandinges6#218]
It might be nice to add an example of making an object iterable.
Although this is implied in the book I did not notice an example of it.

```js
let object = {
  month: 'January',
  year: 2016,
  *[Symbol.iterator]() {
     let keys = Object.keys(this);
     for (let key of keys) {
       yield this[key];
     }
   }
}

for (let propertyValue of object) {
  console.log(propertyValue);
}

// output:
// January
// 2016
```

**Comment by nzakas** [comment]
I'll have to take a look when I review the chapter if adding another example makes sense.

**Comment by nzakas** [comment]
I took a look at adding this and I don't think adding another example aids the reader much. Thanks for the suggestion.
