### ISSUE TITLE
Array size limit did not increase, except for TypedArray.

### ISSUE THREAD

**Issue by ronen-e** [nzakas/understandinges6#219]
You mention in your book that the size limit for Array objects was increased from `2^32-1` to `2^53-1` elements. 
According to the [specs](http://www.ecma-international.org/ecma-262/6.0/#sec-object-type):
```
An integer index is a String-valued property key that is a canonical numeric 
String (see 7.1.16) and whose numeric value is either +0 or a positive integer ≤ 2^53−1.   
An array index is an integer index whose numeric value i is in the range +0 ≤ i < 2^32−1.
```

[TypedArray](http://www.ecma-international.org/ecma-262/6.0/#sec-get-%typedarray%.prototype.length) objects use an internal [[[ArrayLength]]](http://www.ecma-international.org/ecma-262/6.0/#sec-integer-indexed-exotic-objects) *integer index* as their length property and so a TypedArray size limit is indeed 2^53-1.

Standard [Array](http://www.ecma-international.org/ecma-262/6.0/#sec-array-constructor) objects and [Array like](http://www.ecma-international.org/ecma-262/6.0/#sec-array-exotic-objects) objects using an *array index* did not increase their size limit.

**Comment by nzakas** [comment]
Thanks, need to fix that.

**Comment by nzakas** [comment]
This was fixed, just forgot to close this.
