### ISSUE TITLE
Re-assignment of a constant fails silently in non-strict mode

### ISSUE THREAD

**Issue by senthilp** [nzakas/understandinges6#222]
In the [Block Bindings](https://github.com/nzakas/understandinges6/blob/master/manuscript/01-Block-Bindings.md#similarities-and-differences-from-let) chapter there is a statement which says "Attempting to assign a const to a previously defined constant will throw an error, in both strict and non-strict modes". But it looks like re-assignment of a constant fails silently in non-strict mode and throws an error only in strict mode. Also verified it in Chrome and Firefox. The mdn doc also [mentions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const#Examples) the same. May be it will be fixed in the future.

**Comment by nzakas** [comment]
After looking at the spec, I believe the book is correct. There's a function `createImmutableBinding(N,S)` that defines constants and the `S` is for strict mode. The [description](http://www.ecma-international.org/ecma-262/6.0/#sec-environment-records) is:

> If S is true then attempts to access the value of the binding before it is initialized or set it after it has been initialized will always throw an exception, regardless of the strict mode setting of operations that reference that binding. S is an optional parameter that defaults to false.

If you search for `createImmutableBinding` in the spec, you'll come across a lot of instances that look like this:

```
If IsConstantDeclaration of d is true, then
   Let status be lexEnvRec.CreateImmutableBinding(dn, true).
Else,
   Let status be lexEnvRec.CreateMutableBinding(dn, false).
```

So it seems like `S` is always true when creating constants, so it should throw an error upon reassignment even outside of strict mode.

**Comment by senthilp** [comment]
Sounds good. I assume the browser implementations would change in the future to support the spec.

**Comment by nzakas** [comment]
I hope so. :) It looks like this check is already on the [ES6 compat table](https://kangax.github.io/compat-table/es6/) (Bindings -> Const -> Redefining Const is an Error). Looks like very few browsers implement this correctly right now.
