### ISSUE TITLE
chapter 4 typographical error...?

### ISSUE THREAD

**Issue by YoungHyunLee** [nzakas/understandinges6#223]
First...
I can speak english well.. xD..
I translate this repository for korea language because i study english and ECMAScript 6.
so...
my question is...

chapter 4. "## Duplicate Object Literal Properties."
before

A> ### Working with Accessor Properties A> A> Keep in mind that Object.assign() does not create accessor properties on the receiver when a supplier has accessor properties. Since Object.assign() uses the assignment operator, an accessor property on a supplier will become a data property on the receiver. For example: A> A> js A> var receiver = {}, A> supplier = { A> get name() { A> return "file.js" A> } A> }; A> A> Object.assign(receiver, supplier); A> A> var descriptor = Object.getOwnPropertyDescriptor(receiver, "name"); A> A> console.log(descriptor.value); // "file.js" A> console.log(descriptor.get); // undefined A> A> A> In this code, the supplier has an accessor property called name. After using Object.assign(), receiver.name exists as a data property with the value of "file.js". That's because supplier.name returned "file.js" at the time Object.assign() was called.

change this text...

### Working with Accessor Properties

Keep in mind that `Object.assign()` does not create accessor properties on the receiver when a supplier has accessor properties. Since `Object.assign()` uses the assignment operator, an accessor property on a supplier will become a data property on the receiver. For example:

```js
var receiver = {}, 
supplier = { 
	get name() { 
		return "file.js" 
	} 
}; 
```

In this code, the `supplier` has an accessor property called `name`. After using `Object.assign()`, `receiver.name` exists as a data property with the value of `"file.js"`. That's because `supplier.name` returned "file.js" at the time `Object.assign()` was called.

If this text change correct, please update this text.
Thank you. 형님.

**Comment by nzakas** [comment]
Are you referring to `A>`?

**Comment by YoungHyunLee** [comment]
Yes! 
I think...
`A>` is `keyboard enter key`..

**Comment by nzakas** [comment]
`A>` is part of Leanpub Markdown. See https://github.com/nzakas/understandinges6#leanpub-markdown

**Comment by YoungHyunLee** [comment]
oh...
i'm so sorry.. T_
thanks..!!
