### ISSUE TITLE
"Strict mode" reference

### ISSUE THREAD

**Issue by willywongi** [nzakas/understandinges6#227]
While reading the book online, I found a reference to a strict-mode in the text. While I know something about it, I expected some reference or small explanation about it. 
The first occurrence of it is in this chapter: https://github.com/nzakas/understandinges6/blob/master/manuscript/01-Block-Bindings.md#similarities-and-differences-from-let.

While in the introduction you state clearly that the reader should be "already familiar with JavaScript and ECMAScript 5", I think an average reader like myself could use some more information about what "strict mode" is.

**Comment by nzakas** [comment]
I'm sorry, that's outside the scope of the book. Strict mode was introduced in ES5, and there is a lot to it, so you really need to learn about it before reading the book. I'd suggest starting here: https://www.nczonline.net/blog/2012/03/13/its-time-to-start-using-javascript-strict-mode/

**Comment by willywongi** [comment]
Ok, didn't knew it was ES5. Thanks for the help!
