### ISSUE TITLE
__proto__ is a legacy feature and using it is not recommended

### ISSUE THREAD

**Issue by ronen-e** [nzakas/understandinges6#230]
You wrote about the `__proto__` property in the [chapter about objects](https://github.com/nzakas/understandinges6/blob/master/manuscript/04-Objects.md#more-powerful-prototypes).
The `__proto__` feature resides in [Annex B of the ECMAScript specification](http://www.ecma-international.org/ecma-262/6.0/#sec-additional-ecmascript-features-for-web-browsers). This is where they put all those legacy features with wide browser support but problematic nature.

According to the specs it is not recommended to use any of the features in Annex B:
```
These features are not considered part of the core ECMAScript language. Programmers should not use
or assume the existence of these features and behaviours when writing new ECMAScript code.
ECMAScript implementations are discouraged from implementing these features unless the
implementation is part of a web browser or is required to run the same legacy ECMAScript code that 
web browsers encounter.
```
I think it would be great to add a note regarding `__proto__` being a legacy feature to the book.

**Comment by nzakas** [comment]
Good point, I'll make an update.
