### ISSUE TITLE
Exporting objects in modules

### ISSUE THREAD

**Issue by ronen-e** [nzakas/understandinges6#232]
I almost never see any example of exporting objects in ES6 documentation. 
I would love to see some in your book. 
I think that along with the [caveat](https://github.com/nzakas/understandinges6/blob/master/manuscript/14-Modules.md#basic-exporting-and-importing) that while importing looks like destructuring it is not, It would also be helpful to add a note regarding exporting object literals, that although the export syntax may look like an object literal it is not.

This works:
```js
var object = { year: 2014 };
export { object }
export var anotherObject = { year: 2015 }
export default { year: 2016 }
```
This would throw a syntax error exception
```js
export { year: 2016 }
```

I tested the above examples using babel.js latest (version 6)

**Comment by ronen-e** [comment]
@nzakas - a gentle bump on this issue.

**Comment by nzakas** [comment]
I've seen it, I'm just not yet at finishing up the module chapter yet. When I am, I'll take a look.

**Comment by nzakas** [comment]
Unfortunately, I forgot to review this before the book was published, so I can't make a change now.

**Comment by ronen-e** [comment]
😿
