### ISSUE TITLE
Suggestion for section: Inherited Static Members

### ISSUE THREAD

**Issue by robCam** [nzakas/understandinges6#243]
To conclude the _Inherited Static Members_ section it would be beneficial to the reader, (given the previous Square/Rectangle inheritance gists), to in some way make explicit that the static `create()` method should be redefined on the Square class as a result of `Square.create()` behaving in the same manner as `Rectangle.create()` through inheritance. E.g.
```javascript
class Square extends Rectangle {

    constructor(length) {
        super(length, length);
    }

    getArea() {
        return this.length * this.length;
    }

    // override the Rectangle static create method
    static create(length) {
        return new Square(length);
    }
}
```

Redefining the static `create()` method on the Square class (as above) will allow the following previously shown examples to work again:
```javascript
var square = Square.create(3);
console.log(square.getArea());        // 9 instead of NaN
```

**Comment by nzakas** [comment]
Good suggestion, I'll add that.

**Comment by nzakas** [comment]
Book is now complete.
