### ISSUE TITLE
mention return value of Object.assign()

### ISSUE THREAD

**Issue by psalaets** [nzakas/understandinges6#249]
Chapter: 04-Objects.md
Section: The Object.assign() Method

The section says Object.assign() is similar to a function found in many helper libs but it makes no mention of the return value. The code example doesn't use Object.assign()'s return value.

This left me wondering if Object.assign() really *is* similar to e.g. lodash's _.assign() method, so I stopped reading and checked MDN. Not the end of the world but seems like the return value should be mentioned.

**Comment by nzakas** [comment]
I'll see if I can fit it in before it goes to press
