### ISSUE TITLE
An issue in 03-Functions.md

### ISSUE THREAD

**Issue by yanxyz** [nzakas/understandinges6#252]
There is an example in `03-Functions.md` which says:

```js
function add(first = second, second) {
    return first + second;
}

console.log(add(1, 1));     // 2
console.log(add(1));        // throws error
```

 `add(1)` returns `NaN` instead of throwing error in Chrome and Firefox. I think it should be `add(undefined, 1)`:

```js
function add(first = second, second) {
    return first + second;
}

console.log(add(1, 1));     // 2
console.log(add(1));        // NaN
console.log(add(undefined, 1));        // throws error
```

But `add(undefined, 1)` still returns 2 in Firefox.

**Comment by yanxyz** [comment]
Another issue:

```js
let object = {

    // Syntax error: Can't use rest param in setter
    set(...value) {
        // do something
    }
};
```

Here it is a method `object.set()` instead of  a setter. Fix:

```js
let object = {

    // Syntax error: Can't use rest param in setter
    set name(...value) {
        // do something
    }
};
```

**Comment by nzakas** [comment]
Keep in mind that not all browsers correctly implement ES6 right now. 

Your first example is described correctly in the book and is incorrect in the browsers.

The second example looks like a typo. I'll fix that.
