### ISSUE TITLE
Unnecessary redundancy for optional 

### ISSUE THREAD

**Issue by craigmichaelmartin** [nzakas/understandinges6#255]
From the [manuscript](https://github.com/nzakas/understandinges6/blame/8fdd09870938fbade221947dbe905fb5f8fd9372/manuscript/05-Destructuring.md#L523-L538):
> [The] default object needs to have all the same information as the destructured parameters (with the same defaults, to ensure consistent behavior), like the one in this version of the setCookie() function:

```javascript
function setCookie(name, value,
    {
        secure = false,
        path = "/",
        domain = "example.com",
        expires = new Date(Date.now() + 360000000)
    } = {
        secure: false,
        path: "/",
        domain: "example.com",
        expires: new Date(Date.now() + 360000000)
    }
) {
    // ...
}
```

Why not just:
```javascript
function setCookie(name, value,
    {
        secure = false,
        path = "/",
        domain = "example.com",
        expires = new Date(Date.now() + 360000000)
    } = {}
) {
    // ...
}
```

**Comment by nzakas** [comment]
Yeah, I think you're right. This was one of the first sections I wrote back before there were complete implementations to test with, so I probably had to do this way back when but it doesn't look like it has to be done now.

**Comment by craigmichaelmartin** [comment]
I'm happy to make a PR, but imagine you may want to do so to get the wording just right :)

**Comment by nzakas** [comment]
Yes, thanks. :)

**Comment by nzakas** [comment]
Oops, that was ambiguous. I meant yes, I'll make the change.
