### ISSUE TITLE
Clarify wording in around determining string characterCount

### ISSUE THREAD

**Issue by ericlaw1979** [nzakas/understandinges6#258]
`Unfortunately, ECMAScript 6 can't natively determine how many code points a string has`

The wording here tripped me up, in part because the text then presents a regular expression which does so, and regular expressions are "native" to the language.

Maybe change to...

`Unfortunately, ECMAScript 6 does not include a simple method determine how many code points a string has`

Or, even more clearly:

`Unfortunately, even in ECMAScript 6, the length method continues to return the count of code units in a string, not the count of code points. No method was added to determine how many code points a string has`

**Comment by nzakas** [comment]
Thanks, I'll take a look.
