### ISSUE TITLE
Errata: let and const 

### ISSUE THREAD

**Issue by abdulapopoola** [nzakas/understandinges6#263]
The chapter on let/const says they are not hoisted however the language spec says they are:

[The variables are created when their containing Lexical Environment is instantiated but may not be accessed in any way until the variable's LexicalBinding is evaluated.](https://tc39.github.io/ecma262/#sec-let-and-const-declarations)

Should this be updated?

**Comment by getify** [comment]
dupe of #262?

**Comment by abdulapopoola** [comment]
Thanks! Didn't see that initially. Will close.
