### ISSUE TITLE
destructuring with rest does not clone array in node (maybe Babel bug?)

### ISSUE THREAD

**Issue by mperdikeas** [nzakas/understandinges6#267]
Maybe this is a bug in Babel (I am using it with the `es2016` preset) however, the above code does throw an exception:

         const a = [1,2,3]
         const [...v] = a;
         if (a===v)
             throw new Error(); 

The transpiled code is simply:

     const v = a;

**Comment by nzakas** [comment]
Your example doesn't make any sense. This is the example from the book:

```js
let colors = [ "red", "green", "blue" ];
let [ ...clonedColors ] = colors;
console.log(clonedColors);
```

The arrays will not be equal (`===`) because they are different objects, but they will contain the same values.

I don't know what Babel is doing. Try experimenting with the latest version of Chrome.

**Comment by mperdikeas** [comment]
> The arrays will not be equal (===) because they are different objects, but they will contain the same values.

Yeah, that was exactly my point. That the arrays were supposed to be a copy of each other and not in fact the same array. But I guess this is a Babel transpiling thing / bug.
