### ISSUE TITLE
Leanpub formatting number incorrectly

### ISSUE THREAD

**Issue by ronen-e** [nzakas/understandinges6#277]
In the chapter on proxies under [Detecting Array Indices](https://leanpub.com/understandinges6/read#leanpub-auto-solving-the-array-problem) there is a formatting error for the number representing `2^32-1`
The markdown seems ok so I suppose it has to do with specific leanpub flavor
```
A String property name P is an array index if and only if ToString(ToUint32(P)) 
is equal to P and ToUint32(P) is not equal to 232âˆ’1.
```

**Comment by nzakas** [comment]
Looks like I had an emdash instead of a minus sign in there (it was copied from the spec). That's probably the issue.
