### ISSUE TITLE
small wrong

### ISSUE THREAD

**Issue by kiscall** [nzakas/understandinges6#283]
I read your 《Understanding ES6》leanpub.com, and I find a small wrong in Arrow Function, you may write "  \'new\' " to " \'ne\w' ".

**Comment by nzakas** [comment]
I'm sorry, I don't understand what you're saying. Can you be more specific?

**Comment by kiscall** [comment]
Sorry, I am a Chinese student, and my English is poor.
I read your 《understanding ES6》 on https://leanpub.com/understandinges6/read. And I found a small wrong, 
![2016-05-01 9 15 41](https://cloud.githubusercontent.com/assets/10861193/14939524/514eba04-0f7d-11e6-932b-e413b683c54e.png)
look at that comment:

**Comment by nzakas** [comment]
OK, I see. Thank you, I'll fix that.

**Comment by nzakas** [comment]
Should be fixed now.
