### ISSUE TITLE
Loops

### ISSUE THREAD

**Issue by spederiva** [nzakas/understandinges6#292]
Hi Nicholas,

I'm reading your books and it looks very intersting.

In the first chapter talking about loops, you say that in for loop when we are using let, the loop initializer "creates a new variable and initializes it to the value of the variable with the same name"
I think because this you can do something like:

`
```
for (let i = 0; i <= max; i++) {
    let i = 10;

    console.log(i);
}

```

and you will get the value "10", 10 times

but, in contrast, "The for-in and for-of loops work with const because the loop initializer creates a new binding on each iteration through the loop rather than attempting to modify the value of an existing binding"

You also say that const "A const declaration prevents modification of the binding...".

so I think I'm missing something here. 

Can you clarify it in the text?

Thanks

Sebastian

**Comment by nzakas** [comment]
Can you explain what you're confused about?

**Comment by StommePoes** [comment]
Sebastian:
Maybe it's the slight difference... you cannot *modify* a binding on a `const`, but with the for-in/for-of , it makes *complete new bindings* although that's a guess.

**Comment by nzakas** [comment]
Yes, each iteration through the loop creates a new binding. When using `const`, you cannot overwrite that binding inside of the loop.
