### ISSUE TITLE
Did we mean to see ES5 here?

### ISSUE THREAD

**Issue by StommePoes** [nzakas/understandinges6#299]
In chapter 4, under the heading Easy Prototype Access with Super References, the paragraph states

" For example, to override a method on an object instance such that it also calls the prototype method of the same name, you’d do the following in ECMAScript 5:"

The example is then actually ES6, no? It's using `let`, concise methods and `setPropertyOf()`, just no `super`.

I would, in fact, like to see it in ES5, but the intention might have been "ES6 without super" since the following example shows using super instead.

**Comment by nzakas** [comment]
Good catch, I should probably just eliminate "in ECMAScript 5" to keep it simple.
