### ISSUE TITLE
Behaviour of arguments

### ISSUE THREAD

**Issue by anirudh-modi** [nzakas/understandinges6#303]
In the functions chapters, subheading "How Default Parameter Values Affect the arguments Object"
it was mentioned that in ES5, modification of param values effect the argument object, depending on `strict mode` and `non-strict mode`

````javascript
function mixArgs(first, second) {
    console.log(first === arguments[0]);  //true
    console.log(second === arguments[1]); //true
    first = "c";
    second = "d";
    console.log(first === arguments[0]); //true
    console.log(second === arguments[1]); //true
}

mixArgs("a", "b"); // true,true,true,true
mixArgs("a"); // true,true,true,false
mixArgs(); // true,true,false,false
````

However, when I never passed any second parameter it showed a different kind of behaviour even in `non-strict mode`.
I could not understand this dual behaviour, and why it never effected argument object when undefined is passed, even in `non-strict mode`.

Thanks,
Anirudh

**Comment by nzakas** [comment]
I'm sorry, it's really not possible for me to debug code that isn't in the book. All I can say is that the book example is correct (I've double-checked it) and if you're seeing a different behavior in your code, it's likely you're doing something slightly different.

**Comment by anirudh-modi** [comment]
The example in the book is correct, there is no doubt about that, however, the issue arises when I dont pass any value to the function, and then try to check the argument object.

Anyways, Thanks for your valuable time and response.
