### ISSUE TITLE
exporting with a default

### ISSUE THREAD

**Issue by craigmichaelmartin** [nzakas/understandinges6#308]
```javascript
function sum(num1, num2) {
    return num1 + num2;
}

export { sum as default };
```
This is confusing to me, but maybe will elicit a great understanding with a bit of explanation. Instead of the syntax used above, I am accustomed to using `export default sum;` which looks to me like default is a new keyword. In the example above, it looks like default is a special key / variable name (eg, if the function was called `default` you could just `export default`. Is there reason you used the approach you did `export { sum as default }`? Is it worth calling out the `export default sum` approach, and talking to the deeper reason why they both work?

PS - Great book!!!

**Comment by nzakas** [comment]
Sorry, I'm having a bit of trouble following what you're asking.

Are you confused over why `as default` works?

**Comment by nzakas** [comment]
I've tried adding a bit more text in this section (trying to pass this into the publisher this week, sorry for being impatient).

**Comment by craigmichaelmartin** [comment]
Sorry for lack of clarity! 

1. Why does `as default` work in the context `export { sum as default}`.
2. What if I wanted to do a non-default export of an object with a key called default:
```
//const name = 'Nicholas Zakas';
const default = 'John Doe'
export {
  //name,
  default
}
``` 
Would this be imported as `import {default} from 'example'` or `import defaultImportCanBeAnything from 'example'`?
3. Why do you choose to callout the syntax  `export { sum as default}` for default exports without mentioning the syntax `export default sum`?

**Comment by craigmichaelmartin** [comment]
You're fine! I was hoping to prompt you for some greater insight :) Your commit was exactly what I was thinking was lacking for those not quite as in tune!

**Comment by nzakas** [comment]
I honestly just completely forgot about the syntax `export default sum` -- there are so many variations that it's hard to keep track. Thanks for prompting me!
