### ISSUE TITLE
Confusing passage to the next section

### ISSUE THREAD

**Issue by kwasniew** [nzakas/understandinges6#321]
In 03-Functions at the end of the "How Rest Parameters Affect the arguments Object" section there's a sentence: "The next section continues the parameter discussion with the spread operator, which is closely related to rest parameters."
But the next section is "Increased Capabilities of the Function Constructor" and only after that you continue with "The Spread Operator" section.

**Comment by nzakas** [comment]
Yeah, I think there was some reorganizing that went on there.
