### ISSUE TITLE
wrong or not clear description about new.target in Functions chapter

### ISSUE THREAD

**Issue by kuma0605** [nzakas/understandinges6#323]
You give a example below:

function Person(name) {
if (typeof new.target === Person) {
this.name = name; // using new
} else {
throw new Error("You must use new with Person.")
}
}

function AnotherPerson(name) {
Person.call(this, name);
}

var person = new Person("Nicholas");

var anotherPerson = new AnotherPerson("Nicholas"); // error!

"In this code, new.target must be Person in order to work correctly. When new AnotherPerson("Nicholas") is called, new.target is set to AnotherPerson, so the subsequent call to Person.call(this, name) will throw an error even though new.target is defined."

I run code above. When new AnotherPerson("Nicholas") is called, new.target is set to AnotherPerson, that's right,
but the subsequent call to Person.call(this, name) will throw an error because new.target in Person is undefined. One constructor's new.target can't be shared by subsequent call, in my opinion.

According what you describe before that example, I think the new.target is set to undefined when no new operator before a constructor.

**Comment by nzakas** [comment]
Already fixed: https://github.com/nzakas/understandinges6/commit/c15f91c84921ae0b4a6bfe3e22ec91a9d1ee86b7
