### ISSUE TITLE
Some confusion about the regexp flag of 'y'

### ISSUE THREAD

**Issue by zdying** [nzakas/understandinges6#325]
in the article <[Strings and Regular Expressions](https://github.com/nzakas/understandinges6/blob/master/manuscript/02-Strings-and-Regular-Expressions.md)>

> The lastIndex property is only honored when calling methods that exist on the regular expression object, like the exec() and test() methods. Passing the regular expression to a string method, such as match(), will not result in the sticky behavior.

i test it in chrome 52.0.2743.24 by the code

    let reg = /abc\d\s/y;
    let txt = "abc1 abc2 abc3";

    console.log('==== exec ====');
    console.log(reg.exec(txt));
    console.log(reg.lastIndex);

    console.log('==== match ====');
    console.log(txt.match(reg));
    console.log(reg.lastIndex);

the result is:
    
    ==== exec ====
    ["abc1 ", index: 0, input: "abc1 abc2 abc3"]
    5
    ==== match ====
    ["abc2 ", index: 5, input: "abc1 abc2 abc3"]
    10

I tried it, in fact, `exec()` affected the `lastindex`

**Comment by Bamieh** [comment]
sadly regex sticky flag is only supported on firefox for now, and only fully supported on firefox 44 and above.

**Comment by zdying** [comment]
@Bamieh ok. thx
