### ISSUE TITLE
ordered/unordered about set/map not remain same in set/map chapter

### ISSUE THREAD

**Issue by kuma0605** [nzakas/understandinges6#336]
<img width="449" alt="screen shot 2016-08-23 at 11 52 54 am" src="https://cloud.githubusercontent.com/assets/2958589/17879925/2a251c2a-6928-11e6-8e33-bd5da8ab0312.png">
But in summary,
<img width="478" alt="screen shot 2016-08-23 at 11 53 39 am" src="https://cloud.githubusercontent.com/assets/2958589/17879938/43c3adfe-6928-11e6-8bf2-57908dd4c8da.png">

the same description problem about map, it confuses me.

**Comment by nzakas** [comment]
Oops, definitely a typo. I'll look into it.

**Comment by piecioshka** [comment]
Haha! Yestarday I was asked about that: https://twitter.com/piecioshka/status/775399181569622017

😜
