### ISSUE TITLE
Global Block Bindings

### ISSUE THREAD

**Issue by stevepop** [nzakas/understandinges6#338]
On page 15, I ran the following code in my browser;
```
// in a browser
let RegExp = "Hello!";
console.log(RegExp); // "Hello!" 
console.log(window.RegExp === RegExp); // false
const ncz = "Hi!";
console.log(ncz); // "Hi!" 
console.log("ncz" in window); // false
```
What I observed is that `window.RegExp === RegExp` and `"ncz" in window` both evaluated to true in my browser (chrome) as against what is in the book. see screenshot attached
![results](https://cloud.githubusercontent.com/assets/526063/18436232/34a7638e-78ef-11e6-89be-05726159f1e5.png)
![let_const](https://cloud.githubusercontent.com/assets/526063/18436233/34aabfd4-78ef-11e6-91c2-02cb0b90b023.png)
Can this be corrected if this is a mistake or is there any explanation for this that should be added in the book update to help other readers?
Thanks.

**Comment by hunter2009** [comment]
```
// in a browser
let RegExp = "Hello!";
console.log(RegExp); // "Hello!"
console.log(window.RegExp === RegExp); // false
const ncz = "Hi!";
console.log(ncz); // "Hi!"
console.log("ncz" in window); // false
```
**```
Hello!
false
Hi!
false
```**
I got this....

**Comment by stevepop** [comment]
@hunter2009  Okay, I was running mine already compiled to es2015 preset. I guess that is the reason I was getting a different value. Thanks
