### ISSUE TITLE
Typo - Chapter 8: Iterators and Generators

### ISSUE THREAD

**Issue by vishallama** [nzakas/understandinges6#342]
Under the section [The Spread Operator and Non-Array Iterables](https://github.com/nzakas/understandinges6/blob/master/manuscript/08-Iterators-And-Generators.md#the-spread-operator-and-non-array-iterables), in the second paragraph, the sentence

> All values are read from the iterator and inserted into the array in the order in which values **where** returned from the iterator.

should probably read

> All values are read from the iterator and inserted into the array in the order in which values **were** returned from the iterator.

**Comment by nzakas** [comment]
Thanks, I'll get that fixed.
