### ISSUE TITLE
Syntax typo - Chapter 11: Promises and Asynchronous Programming

### ISSUE THREAD

**Issue by vishallama** [nzakas/understandinges6#343]
In section [Creating Unsettled Promises](https://github.com/nzakas/understandinges6/blob/master/manuscript/11-Promises.md#creating-unsettled-promises), the following code snippet has a semicolon missing when calling the `setTimeout` function. Even though the code snippet runs just fine without the semicolon, for the sake of consistency it might be better to add one.

```javascript
// add this function to the job queue after 500ms have passed
setTimeout(function() {
    console.log("Timeout");
}, 500)

console.log("Hi!");
```
Suggested correction:
```javascript
// add this function to the job queue after 500ms have passed
setTimeout(function() {
    console.log("Timeout");
}, 500);

console.log("Hi!");
```

**Comment by Bamieh** [comment]
Its okay to not use a semicolon break after a `name`, `string`, `number`, or `)` `]` `++` `--`

**Comment by nzakas** [comment]
I think the point is that for consistency, there should be a semicolon there. I agree.
