### ISSUE TITLE
Small grammatical correction - Chapter 13: Encapsulating Code with Modules

### ISSUE THREAD

**Issue by vishallama** [nzakas/understandinges6#344]
In the section [Browser Module Specifier Resolution](https://github.com/nzakas/understandinges6/blob/master/manuscript/13-Modules.md#browser-module-specifier-resolution), the first sentence

> All of the examples to this point in the chapter...

may be written as follows,

> All of the examples **up** to this point in the chapter...

**Comment by nzakas** [comment]
This is actually correct grammar. There's no need for "up" in this context.
