### ISSUE TITLE
Are maps unordered key-value pairs?

### ISSUE THREAD

**Issue by eboCode** [nzakas/understandinges6#347]
Am really enjoying your book's fine intro to the world of ES6, although I was a little puzzled with an apparent contradiction in three descriptions of the Map data structure, listed below, with emphasis added.

The next-to-last paragraph on page 136 of the PDF print version starts out:

> Maps are **unordered** key-value pairs where the key can be any data type.

On page 129, just under the subhead 'Maps in ECMAScript 6,' is:

> The ECMAScript 6 Map type is an **ordered** list of key-value pairs, where the key and the value can be any type.

...and page 132 starts with:

> The callback passed to forEach() receives each key-value pair **in the order in which the pairs were inserted** into the map. 

Does the page 136 definition with '**unordered**' have an error, or would it mean something slightly different in context?

**Comment by rwaldron** [comment]
> Maps are unordered key-value pairs where the key can be any data type.

Looks like a typo.

**Comment by nzakas** [comment]
Yeah, it's a typo that was reported here:
https://github.com/nzakas/understandinges6/issues/336

@eboCode I'm guessing that you're reading the No Starch Press ebook? Unfortunately, have no direct control over that but I did report this as errata to them so it can be fixed in future printings. It's already been fixed in the online version.

**Comment by eboCode** [comment]
@rwaldron Thanks!

@nzakas Thank you for confirming that!

No Starch ebook? Sort of... am reading the No Starch print copy (so retro, moi), often without easy access to your online version, but will keep that in mind, thanks.

Also, when I clicked the Issues link on this site, I actually missed seeing the '123 Closed' link in the secondary navbar below it, but it's great to be aware of it now and to know about more resources for checking on errata. On many publisher's sites (e.g., http://shop.oreilly.com/product/0636920030515.do), the Errata links are way less visible, over in the right sidebar for example, and much harder to use. Props to you on using GitHub!

**Comment by nzakas** [comment]
Ah, I guess I always assume people are reading ebooks when they file issues here, shame on me. (I actually prefer print books, too.)

For future reference, everything that No Starch is aware of is listed here: https://www.nostarch.com/ecmascript6#updates

Anything I get submitted on GitHub eventually makes its way to that page if it's a problem with the No Starch version.
