### ISSUE TITLE
Chapter 12, The ownKeys Trap section has a problem

### ISSUE THREAD

**Issue by Summerlve** [nzakas/understandinges6#348]
the first four logs must be:
1
name
1
name

not yours:
1
proxy
1
proxy

**Comment by nzakas** [comment]
What version of the book are you reading? (print, ebook, online, No Starch or Leanpub)?

What page are you referring to?

**Comment by Summerlve** [comment]
The github online version , 12-Proxies-and-Reflection , The ownKeys Trap , codes follows:
`let proxy = new Proxy({}, {   
     ownKeys(trapTarget) {       
         return Reflect.ownKeys(trapTarget).filter(key => {           
             return typeof key !== "string" || key[0] !== "_";       
         });   
     } 
});

let nameSymbol = Symbol("name");

proxy.name = "proxy";
proxy._name = "private"; 
proxy[nameSymbol] = "symbol";

let names = Object.getOwnPropertyNames(proxy),    
     keys = Object.keys(proxy);    
     symbols = Object.getOwnPropertySymbols(proxy);

console.log(names.length);      // 1 
console.log(names[0]);          // "proxy"

console.log(keys.length);      // 1
console.log(keys[0]);          // "proxy"

console.log(symbols.length);    // 1 
console.log(symbols[0]);        // "Symbol(name)"
`
