### ISSUE TITLE
symbol property is unrelated to enumerable 

### ISSUE THREAD

**Issue by hax** [nzakas/understandinges6#352]
In [06-Symbols](https://github.com/nzakas/understandinges6/blob/master/manuscript/06-Symbols.md)

> The property is created as nonenumerable, which is different from computed properties created using nonsymbol names.

I don't find spec say that, and both chrome and ff report enumerable in example
```js
// use a computed object literal property
let person = {
    [firstName]: "Nicholas"
};
console.log(Object.getOwnPropertyDescriptor(person, firstName)) // {enumerable: true, ...}
```

**Comment by nzakas** [comment]
Yeah, that's wrong. I think that was probably from one of the early drafts on symbols before I really understood what they were. :) Thanks, I'll fix that.
