### ISSUE TITLE
ordinary object change to exotic object?

### ISSUE THREAD

**Issue by hax** [nzakas/understandinges6#353]
In [06-Symbols](https://github.com/nzakas/understandinges6/blob/master/manuscript/06-Symbols.md)

> Overwriting a method defined with a well-known symbol changes an ordinary object to an exotic object because this changes some internal default behavior. There is no practical impact to your code as a result, it just changes the way the specification describes the object.

It's unclear for me that an object can be changed from ordinary object to exotic object. All exotic object mentioned in spec (like proxy exotic object, or array exotic object) seems very static. And I'm not sure overriding well-known symbols can "change" the default behavior, it's more like customization rather than "change".

**Comment by nzakas** [comment]
The term "exotic object" just means that the object has some nonstandard behavior, so by introducing nonstandard behavior to an ordinary object, you are creating an exotic object.

**Comment by hax** [comment]
I'm still not sure about that, for example, [this article](http://www.2ality.com/2015/02/es6-classes-final.html) said:

>  In general, exotic objects can be created from scratch, but you can’t convert an existing normal object into an exotic one.

And in [this discussion](https://esdiscuss.org/topic/exotic-object), it seems "exotic" term is introduced to replace "native method / host method".

**Comment by nzakas** [comment]
As far as I know, there is no requirement of an object needing to be exotic from creation. The spec definition for [exotic object](https://tc39.github.io/ecma262/#sec-exotic-object) is: 

> object that does not have the default behaviour for one or more of the essential internal methods
