### ISSUE TITLE
Need clarification

### ISSUE THREAD

**Issue by hax** [nzakas/understandinges6#354]
In [06-Symbols](https://github.com/nzakas/understandinges6/blob/master/manuscript/06-Symbols.md)

> The method is defined on Function.prototype so that all functions inherit the default behavior for the instanceof property. The Symbol.hasInstance property itself is defined as nonwritable and nonconfigurable as well as nonenumerable, to ensure it doesn't get overwritten by mistake.

"The Symbol.hasInstance property itself", whether it mean the `hasInstance` property on `Symbol` or `Symbol.hasInstance` property on `Function.prototype`? Both are nonwritable, nonconfigurable and nonenumerable.

**Comment by nzakas** [comment]
Hmm yeah, that is a bit confusing. I meant to say that `Function.prototype[Symbol.hasInstance]` is nonwritable, nonconfigurable, and nonenumerable. I'll clear that up.
