### ISSUE TITLE
Missing special case of ±0 in Sets and Maps

### ISSUE THREAD

**Issue by hax** [nzakas/understandinges6#355]
In [07 Sets and Maps](https://github.com/nzakas/understandinges6/blob/master/manuscript/07-Sets-And-Maps.md)
> (Internally, the comparison uses the Object.is() method discussed in Chapter 4 to determine if two values are the same.)

It's a little misguide because Set/Map treat +0 and -0 as equal, but `Object.is` not.

**Comment by rwaldron** [comment]
Confirm. Set, Map, WeakSet and WeakMap all use the SameValueZero comparison algorithm. Object.is uses SameValue. The difference between the two is specifically in treatment of +0/-0

**Comment by nzakas** [comment]
Thanks, I'll get an update in when I'm able.
