### ISSUE TITLE
Incorrect example for "The new.target MetaProperty"

### ISSUE THREAD

**Issue by sagittarius-rev** [nzakas/understandinges6#357]
```js
function Person(name) {
    if (typeof new.target === Person) {
        this.name = name;   // using new
    } else {
        throw new Error("You must use new with Person.")
    }
}

function AnotherPerson(name) {
    Person.call(this, name);
}

var person = new Person("Nicholas");
var anotherPerson = new AnotherPerson("Nicholas");  // error!
```

This example will throw a error at `var person = new Person("Nicholas");` , instead of at `var anotherPerson = new AnotherPerson("Nicholas")` , because the code `if (typeof new.target === Person) {` is incorrect.

The example must be fixed to make it work, like this:
```js
if (new.target === Person) {
```

**Comment by nzakas** [comment]
Oops, you're right, that's a mistake. Thanks, I'll get that fixed.
