### ISSUE TITLE
Tail call optimization in step()

### ISSUE THREAD

**Issue by jr-grenoble** [nzakas/understandinges6#360]
Hi Nicholas,

A minor suggestion that some might have already suggested (couldn't find trace of it though):

In your examples on asynchronism, you use a recursive `step()` function. You could easily make it tail recursive by calling `return step();` instead of bland `step();` and having a `return true;` statement instead of falling through the end of the of the function.

This would allow your scheduler (`run()` function) to work with non asynchronous generators that operate over large collections (e.g. used as fake generators for robustness testing) or within applications meant to run for very long durations.

I hope you're beating Lyme!
Thanks for your great books!

— jr
ps: if my suggestion is useless, especially because of my misunderstanding the point, please let me know.

**Comment by nzakas** [comment]
Thanks for the suggestion and the kind words. I'm going to keep the example as-is, as I think making this change might be more confusing than leaving it.
