### ISSUE TITLE
Something wrong with arrow function

### ISSUE THREAD

**Issue by yaoweiprc** [nzakas/understandinges6#363]
As it is said in section 03-Functions:

> If the arrow function is contained within a nonarrow function, `this` will be the same as the containing function; otherwise, `this` is undefined.

but according to what I tried on Chrome 55
`this` refers to `window` if the arrow function is not contained within any nonarrow function instead of undefined.

**Comment by nzakas** [comment]
Yeah, that's a bit confusing. It should say `this` is the equivalent of `this` in the global scope, not `undefined`.
