### ISSUE TITLE
weakSet throw error has change

### ISSUE THREAD

**Issue by joy-yi0905** [nzakas/understandinges6#364]
> In a WeakSet instance, the add() method, has() method, and delete() method all throw an error when passed a non-object.

The `add()` method will throw an error, but `has()` and `delete()` do not .

```javascript
var arr = [[1, 3], {}],
    weakSet = new WeakSet(arr);

console.log(weakSet); // WeakSet {[1, 3], {}}
console.log(weakSet.has(1)); // false
console.log(weakSet.delete(1)); // false

weakSet.add(1); // error: Invalid value used in weak set
```

**Comment by nzakas** [comment]
Oops, looks like I misread the spec. Thanks, I'll get that fixed.
