### ISSUE TITLE
"Anonymous" concise methods -> confusing

### ISSUE THREAD

**Issue by tdd** [nzakas/understandinges6#368]
Hi Nicholas,

*(finally taking the time to feed all this back in GH issues, as per e-mails we exchanged a few weeks ago)*

*Location: Chapter 4 > Page 69 > "Concise Methods" > Last paragraph*

You're stating the `sayName()` method is "assigned an anonymous function expression," which may well be the case mid-implementation, but concise methods are immediately auto-named to the identifier before the parens, something you actually describe in the note following near the top of the next page.

It seems to me the "anonymous" qualifier here is counter-productive, something more of an internal, transient implementation detail than a useful external information.

**Comment by nzakas** [comment]
I think calling these anonymous functions is correct, because you can't do this:

```js
var p = {
   method() {
    return method();  // error, no reference called "method"
  }
};
```

If it weren't anonymous, there would be some reference you could grab to use it directly. Having a `name` property doesn't necessarily mean the function isn't anonymous.
