### ISSUE TITLE
Make spread-based array cloning more idiomatic?

### ISSUE THREAD

**Issue by tdd** [nzakas/understandinges6#372]
Hi Nicholas,

*Location: Chapter 5 > Page 93 > "Rest Items" > last code example*

You’re showing a rest-based shallow array cloning. It's great, but I was surprised by this take (resting on the lvalue) when I keep seeing everywhere a spread-based approach:

```js
const clonedColors = [...colors]
```

Do you think this example would be better this way? It seems more in line with the common practice to me, but I don't have hard usage numbers to back this up (and even if I did, your call! 😉 )

**Comment by tdd** [comment]
(also, I wonder why the heck RS6 demanded rests were only allowed in final position, as they could be anywhere in a list without ambiguity as long as they were the unique rest in there; see Ruby, for instance)

**Comment by tdd** [comment]
Mistakenly closed this directly…

**Comment by nzakas** [comment]
The example you give is the *spread* operator whereas this section is about the *rest* operator, so a spread operator example is a bit out of place here.
