### ISSUE TITLE
Slight confusion between function and constructor?

### ISSUE THREAD

**Issue by tdd** [nzakas/understandinges6#374]
Hi Nicholas,

*Location: Chapter 6 > Page 112 > "The Symbol.toPrimitive method" > first paragraph post-code*

You're building instance of the `Temperature` constructor, and they behave differently depending on the primitive hint (string mode, etc.). Great.

But you explain that *”the `Temperature()` function returns the temperature with…”*. It seems a bit confusing to me. This is a constructor, it does not return primitive-hint-based contents, its `Symbol.toPrimitive` implementation method does. Considering how laser-precise your wording usually is, I was wondering whether this was an oversight?

**Comment by nzakas** [comment]
Yeah, probably fatigue setting in after nearly three years of writing this book. I can't even imagine what I was thinking when I wrote this part, definitely needs some cleanup.
