### ISSUE TITLE
Mention `Set#add()` chains?

### ISSUE THREAD

**Issue by tdd** [nzakas/understandinges6#375]
Hi Nicholas,

*Location: Chapter 7 > Page 123 > "Creating Sets and Adding Items" > Top of the page*

Your `add()` examples all use single calls. I thought it may be nice to mention `add()` chains, so it returns the (possibly-mutated) `Set`.

**Comment by nzakas** [comment]
That would require more significant changes than I'm willing to introduce at this point (it's hard to describe this in errata). Good suggestion, unfortunately it's just too late in the process for such a change.
