### ISSUE TITLE
Delegating yields to generators or iterators?

### ISSUE THREAD

**Issue by tdd** [nzakas/understandinges6#377]
Hi Nicholas,

*Location: Chapter 8 > Page 159 > "Delegating Generators" > Top paragraph and note*

You state that (in this code, admittedly) *“the extra yield statement explicitly outputs the returned value from the `createNumberIterator()` generator”*, and the note below states you can `yield*` directly on strings.

It it my understanding you can `yield*` on absolutely *any* iterator (so generators are just one case, really), so on anything that implements `[Symbol.iterator]`. Strings, arrays, NodeLists, Sets, Maps, etc.  Shouldn't this note emphasize that broader scope?

**Comment by nzakas** [comment]
I'm not sure the note is the right place to call out that information, but I'll take a look. I can at least add a bit more about this somewhere in the section.
