### ISSUE TITLE
Generators… but no laziness?

### ISSUE THREAD

**Issue by tdd** [nzakas/understandinges6#378]
Hi Nicholas,

This is a general remark on chapter 8. IMHO, one of the cool aspects of generators lies in their letting us do lazy computation / traversal in JS. I don't recall having seen any reference of / example about that in this chapter, which I think is too bad. I'd have loved to see a cool example 😁

**Comment by nzakas** [comment]
Thanks for the suggestion. I'm not adding any new content to the book, only fixing typos and adding clarifications. Otherwise, I'd never get to stop.

**Comment by tdd** [comment]
Indeed!
