### ISSUE TITLE
Anonymous class… is not anonymous

### ISSUE THREAD

**Issue by tdd** [nzakas/understandinges6#379]
Hi Nicholas,

*Location: Chapter 9 > Page 170 > "A Basic Class Expression" > first par post-code*

So your code has an anonymous class expression:

```js
let PersonClass = class { … }
```

Then you state that *“In anonymous class expressions, as in the preceding example, `PersonClass.name` is an empty string”*. That is incorrect.

Aside from anonymous callbacks, pretty much every function production in ES6 is auto-named, usually by virtue of its assignment, be it direct or through destructuring or default value. In the particular example you have, `PersonClass.name` is in fact `"PersonClass"`.

I think the only way you could get a truly anonymous class would be by live-defining it as a function argument.

**Comment by nzakas** [comment]
Yeah, I think I mixed up a couple of sentences there.
