### ISSUE TITLE
Differences between ES6/ES5 built-in inheritance… Was there a 2nd aspect?

### ISSUE THREAD

**Issue by tdd** [nzakas/understandinges6#380]
Hi Nicholas,

*Location: Chapter 9 > Page 184 > "Inheriting from build-ins" > Penultimate par*

You say *“the inheritance model of classes is slightly different […], in two significant ways”*. You then go ahead and explain the init-sequence difference between ES5 and ES6. But I fail to see anything in that section that clearly stands out as a *second* significant difference.  What did you have in mind?

**Comment by nzakas** [comment]
The two ways are:

1. How the value of `this` is created
2. When `this` is modified by the derived constructor

I know it doesn't read particularly clear now that I'm looking at it again, but the two ways are definitely stated. I think I can just remove "in two significant ways" and that will eliminate any confusion.
