### ISSUE TITLE
Confusing/misleading `Promise.all` order explanation

### ISSUE THREAD

**Issue by tdd** [nzakas/understandinges6#383]
Hi Nicholas,

*Location: Chapter 11 > Page 234 > "The Promise.all() method" > first par below code*

You say *“The values are stored in the orider in which the promises resolved”*, which is clearly a time-based ordering, and would be terribly harmful / useless if it were true. Values are stored in the order of the promises array passed to `Promise.all()`, obviously, so we can match per-position, a much more useful (if only for array destructuring of the resolve callback arg) approach.

That is very likely an honest mistake attributable to fatigue 😉

**Comment by nzakas** [comment]
Yeah, clearly not thinking very well at this point. I'll fix it.
