### ISSUE TITLE
Error in "02-Strings-and-Regular-Expressions.md"

### ISSUE THREAD

**Issue by Phrancis** [nzakas/understandinges6#385]
In the sub-section titled [Methods for Identifying Substrings](https://github.com/nzakas/understandinges6/blob/master/manuscript/02-Strings-and-Regular-Expressions.md#methods-for-identifying-substrings), there is an error in the following sentence that immediately follows the examples:

> The first three calls don't include a second parameter, so they'll search the whole string if needed. 

The "three" should instead be "six" based on the examples provided.

**Comment by nzakas** [comment]
Oops, thanks for the heads up.
