### ISSUE TITLE
Built-in or Exotic?

### ISSUE THREAD

**Issue by tdd** [nzakas/understandinges6#386]
Hi Nicholas,

*Location: Chapter 12 > Page 243 > Second par*

The text says *“To allow developers to create built-in objects…”* but this seems like a contradiction in terms, if your definitions of *Object Categories* on page 68 hold: you state there that Built-In Objects are *“present in a JS execution environment when a script begins to execute”*, which clearly happens before any userland/developer code.

From what I understand of the various object categories you describe, it seems to me proxies are more of a way to build *Exotic Objects*: objects whose internal behavior differs from the standard objects in some way.

What do you think?

**Comment by nzakas** [comment]
oops yeah, that looks like some bad edits changed the meaning of what I had there. I'll fix that.
