### ISSUE TITLE
So, does the `ownKeys` trap impact `Object.keys()` or not?

### ISSUE THREAD

**Issue by tdd** [nzakas/understandinges6#387]
Hi Nicholas,

*Location: Chapter 12 > Page 262 > "The ownKeys trap" > last par of section*

You state that *“[the ownKeys proxy trap] doesn’t affect more commonly used operations, such as the `for-of` loop and the `Object.keys()` method”*. Just in the par before, you clearly state a partial opposite: that `Object.keys()` is impacted. Which is true?

My own testing, plus spec reading, clearly show impact on `Object.keys()`or, for that matter, `Object.assign()` behavior. As for the `for-of` loop, considering it's based on the object's implementation of `[Symbol.iterator]`, it makes sense that `ownKeys` plays no role.

So there's a weird contradiction in the text here…

**Comment by nzakas** [comment]
Yeah, I know what happened there. The first draft said that `Object.keys` wasn't affected, and then I went back and fixed that in every place except this one.
