### ISSUE TITLE
Strange markdown formatting on mobile Github version 

### ISSUE THREAD

**Issue by Phrancis** [nzakas/understandinges6#390]
Following screenshot is from Chapter 4, as you can see it introduces some `A>` in front of certain sections and messes up the markdown:

![screenshot_20170223-183057](https://cloud.githubusercontent.com/assets/8539648/23283895/8917230e-f9f6-11e6-951c-32570287407c.png)

**Comment by Phrancis** [comment]
Update: I had someone test it on iOS and Windows Phone and confirmed the issue also happens with those. I sent a message to Github Support via Twitter to see if this is a known issue with their mobile platform.

**Comment by Phrancis** [comment]
It looks like this is not a GitHub issue but rather an issue with the source markdown. Looking at the source for the above mentioned section:

```
A> ### Working with Accessor Properties
A>
A> Keep in mind that `Object.assign()` doesn't create accessor properties on the receiver when a supplier has accessor properties. Since `Object.assign()` uses the assignment operator, an accessor property on a supplier will become a data property on the receiver. For example:
A>
A> ```js
A> var receiver = {},
A>     supplier = {
A>         get name() {
A>             return "file.js"
A>         }
A>     };
A>
A> Object.assign(receiver, supplier);
A>
A> var descriptor = Object.getOwnPropertyDescriptor(receiver, "name");
A>
A> console.log(descriptor.value);      // "file.js"
A> console.log(descriptor.get);        // undefined
A> ```
```

This added `A> ` is present in other pages in the book as well. Perhaps it was introduced accidentally? Fixing it should be a matter of simply finding all the `A> ` in the source and deleting them.

**Comment by roblarsen** [comment]
That's Leanpub markdown.  This has come up a few times before (#195, etc.)

**Comment by nzakas** [comment]
Exactly
