### ISSUE TITLE
'arguments' object is affected in the ES5's strict mode

### ISSUE THREAD

**Issue by nobso** [nzakas/understandinges6#396]
Hi @nzakas ,

> How Default Parameter Values Affect the arguments Object
   ECMAScript 5's strict mode, however, eliminates this confusing aspect of the arguments object. In strict mode, the arguments object does not reflect changes to the named parameters.
 
The nuance is that if the parameter that's being passed is an object instead of a primitive, then the argument (object properties) can be modified even in the ES5's strict mode

```javascript
'use strict';
function mixArgs (first) {
    console.log(first.a === arguments[0].a); // true
    first.a = 'b';
    console.log(first.a === arguments[0].a); // true
}

mixArgs({ a: 'a' });
```

**Comment by getify** [comment]
Your code isn't demonstrating anything about the `arguments` object itself being affected (or not affected). Your code only demonstrates that, given a reference to an object, you can mutate its contents by reference. That's an entirely different thing, and totally unrelated either to strict mode or to the `arguments` object at hand.

**Comment by nobso** [comment]
Hi @getify,
Thanks for the response.

```javascript
    first.a = 'b';
    
    // Isn't the 'arguments' object affected here? 
    console.log(first.a === arguments[0].a); // 'b' === 'b' 
```

As @nzakas stated (at https://github.com/nzakas/understandinges6/blob/master/manuscript/03-Functions.md) arguments object seems to be affected.

> The arguments object is always updated in nonstrict mode to reflect changes in the named parameters. Thus, when first and second are assigned new values, arguments[0] and arguments[1] are updated accordingly, making all of the === comparisons resolve to true.
> 
> ECMAScript 5's strict mode, however, eliminates this confusing aspect of the arguments object. In strict mode, the arguments object does not reflect changes to the named parameters. Here's the mixArgs() function again, but in strict mode:

Please help me understand if i've misunderstood this part.

**Comment by getify** [comment]
The arguments object is not affected. An object referenced by one of the entries in arguments is affected. These are entirely different phenomena.

**Comment by nobso** [comment]
```js
let profile = {
   name: 'x'
};
profile.name = 'y';
```
here, don't we say that profile object is modified? Isn't it same as 'arguments'? 

It behaves like 'const',  like primitive values cannot be changed but object's properties.

**Comment by getify** [comment]
```js
var arr = {};
arr[0] = { a: 2 }; 
arr[0].a = 3;
```

Which object was changed/mutated, the object referenced by `arr` or the object referenced by `arr[0]`?

Answer: `arr` is not affected, only `arr[0]`.

**Comment by nobso** [comment]
I see your point. Thanks Kyle.

**Comment by nzakas** [comment]
Sorry, I’ve been dealing with health issues and am just getting back to reviewing issues. @getify’s explanation is perfect. Thanks!
