### ISSUE TITLE
Incorrect output of an example in Chapter 11

### ISSUE THREAD

**Issue by wdscxsj** [nzakas/understandinges6#397]
Hello Nicholas,

For the last example of *11-Promises.md > The Promise.race() Method*:

```
let p1 = new Promise(function(resolve, reject) {
    resolve(42);
});

let p2 = Promise.reject(43);

let p3 = new Promise(function(resolve, reject) {
    resolve(44);
});

let p4 = Promise.race([p1, p2, p3]);

p4.catch(function(value) {
    console.log(value);     // 43
});
```

the output should be empty, I suppose? Since `p1`'s executor is executed immediately, `p1` is resolved strictly before `p2` gets rejected. And because `p4` doesn't set up `then()`, the result is lost and `p4` is silently resolved.

A simple fix is to add a delay to `p1`'s executor, e.g., replacing the 2nd line of code with:

```
setTimeout(function() { resolve(42); }, 100);
```

**Comment by pageYe123** [comment]
@wdscxsj The example is exactly false with the wrong console result.
And the explaination is wong too since [new Promise callback actually is invoked synchronously](https://stackoverflow.com/questions/29963129/is-javascript-promise-callback-executed-asynchronosuly/29964540#29964540):
> Even though p1 and p3 are fulfilled, those results are ignored because they occur after p2 is rejected

 

@nzakas wish improvement~:smile_cat:
e.g. the right example could be this : 
```
let p1 = Promise.resolve().then(function(){return 42});
//                                                  ^^^^^^^^^^^^^^^^^^^^ asynchronous

let p2 = Promise.reject(43);

let p3 = Promise.resolve(44);

let p4 = Promise.race([p1, p2, p3]);

p4.then(console.log, console.error);
```

**Comment by nzakas** [comment]
Yes, this is an error. The example was written before promises were implemented so I was guessing how it would work. I was attempting to show that a rejection occurring first would override the other promises. I’ll need to think of a better example.
