### ISSUE TITLE
A better way to detect 'u' flag for RegExp

### ISSUE THREAD

**Issue by marjune163** [nzakas/understandinges6#413]
For chapter 2, "Determining Support for the u Flag" for `RegExp`,
the example code uses try/catch to test if `u` flag is supported. I'm wondering if we could detect this feature by examining the `unicode` property on RegExp object, like:
```javascript
function hasRegExpU() {
    var pattern = new RegExp("^");
    return ('unicode' in pattern);      
}
```

**Comment by Bamieh** [comment]
@marjune163 indeed you can do that in addition to detecting all of the other flags, the unicode flag was added in ECMAScript 2015, so previous versions will return `undefined` while es6 + will return `true` or `false`.

**Comment by marjune163** [comment]
Thanks a lot!
