### ISSUE TITLE
Chapter 13: default export in "export * from .."

### ISSUE THREAD

**Issue by dongbohu** [nzakas/understandinges6#414]
Line 317 of `13-Modules.md`:
```
By exporting everything, you're including the default as well as any named exports, 
which may affect what you can export from your module. For instance, if `example.js` 
has a default export, you'd be unable to define a new default export when using this 
syntax.
```

But according to step **7.d.i** of ES6 standard: 
http://www.ecma-international.org/ecma-262/6.0/#sec-getexportednames 
The `default` in `example.js` will be skipped by "export * from .." statement, so a user is still able to define his/her own "default" in current module.

**Comment by nzakas** [comment]
Thanks, I’ll get that fixed.

**Comment by shadowz10** [comment]
@nzakas  Hello, I would like to translate to Spanish but I do not know how. I would like to do it by means of pull request :)

**Comment by nzakas** [comment]
@shadowz10 see https://github.com/nzakas/understandinges6#can-i-acquire-translation-rights.
