### ISSUE TITLE
Chapter 2: Strings - Template Literal Strawman proposal - dead link

### ISSUE THREAD

**Issue by ronen-e** [nzakas/understandinges6#443]
In chapter 2 under **Template Literals** section there is the link to 

[template literal strawman](http://wiki.ecmascript.org/doku.php?id=harmony:quasis)

However, that link is not working

**Comment by nzakas** [comment]
Sadly, it looks like the domain is no longer maintained and I can't find any new mirrors. You'd need to go into the Wayback machine to find it: https://web.archive.org/web/20170114115928/http://wiki.ecmascript.org/doku.php?id=harmony:quasis
