### ISSUE TITLE
Potential Typo in Symbol chapter 6

### ISSUE THREAD

**Issue by ronen-e** [nzakas/understandinges6#447]
**issue**
At the end of the section about `Symbol.toStringTag` I think the wording 

> Even though `Symbol.toStringTag` is overwritten for arrays in this example, the call to `Object.prototype.toString()` results in `"[object Magic]"` instead. 

should be changed due to the use of *Even though* and *instead* which creates a different meaning.

**Solution:**
maybe something like:

> **Since** `Symbol.toStringTag` is overwritten for arrays in this example, 
the call to `Object.prototype.toString()` 
results in `"[object Magic]"` **instead of `"[object Array]"`**.

**Comment by nzakas** [comment]
Can you explain more about why you think the wording is confusing?

**Comment by ronen-e** [comment]
the wording "Even though ... instead " indicates contrast
similar to using "but"

When I read the sentence it was like reading
> `Symbol.toStringTag` is overwritten for arrays in this example, **but** the call to `Object.prototype.toString()` results in `"[object Magic]"`. 

However the result `"[object Magic]"` is the expected result. 
So there is no contrast and no need for **but** , 
Adding **but** is somewhat confusing, at least for me.

I would understand the sentence better if the meaning was:
> `Symbol.toStringTag` is overwritten for arrays in this example, **therefore** the call to `Object.prototype.toString()` results in `"[object Magic]"`.

**Comment by nzakas** [comment]
Okay, thanks, let me think about this a bit. My brain is having a lot of trouble with converting abstract ideas into words due to some health issues, so it's a bit harder for me to figure out which words make sense (let alone trying to figure out what I meant by my original words).

**Comment by nzakas** [comment]
Okay, brain is a bit better today. I would change "even though" to "because" and otherwise use your suggested correction in the first comment.
