### ISSUE TITLE
Potential typo in 09 - Classes

### ISSUE THREAD

**Issue by ronen-e** [nzakas/understandinges6#450]
in the section **Class-Like Structures in ECMAScript 5** the following sentence is somewhat confusing:

> In this code, `PersonType` is a constructor function that creates a single property called `name`.

**_Reason_**:
The return value of `PersonType` is unclear.
the constructor function returns an **instance** with a single property and returns it.

**_Solution_**:
> In this code, `PersonType` is a constructor function that creates **an instance with** a single property called `name`.

The text above gives a clearer meaning for the return value of the `PersonType` constructor.

**Comment by nzakas** [comment]
Yup, definitely some missing words in there. Thanks for letting me know.
