### ISSUE TITLE
Potential typo in 09 - Classes - innerHTML method

### ISSUE THREAD

**Issue by ronen-e** [nzakas/understandinges6#451]
In Chapter 9 - Classes, line 308, under the section "Accessor Properties" there is a potential typo

> It has both a getter and setter for `html` that delegates to the `innerHTML` **method** on the element itself.

**Reason**:
Element.innerHTML is not a **function/method**. 
It is considered a string valued property.

**Solution**:
> It has both a getter and setter for `html` that delegates to the `innerHTML` **property** on the element itself.

**Comment by nzakas** [comment]
Thanks!
