### ISSUE TITLE
Potential type in 09 - Classes - [[Construct]] full description

### ISSUE THREAD

**Issue by ronen-e** [nzakas/understandinges6#452]
**Problem**
the term `[[Construct]]` appears 4 times in chapter 9.

The full description is given only once, on line 76:
```
an internal `[[Construct]]` method
```
The other instances lack any description apart from `[[Construct]]`
- line 661
> a function with `[[Construct]]` and a prototype. 
-  line 684
> Since `Rectangle` has `[[Construct]]` and a prototype,
- line 756
> there is no `[[Construct]]` to call.

**Reason**:
lines 661,684,756 would be better understood if a clearer description would be provided as in line 76

**Solution**:
Use the more expansive description

- line 661
> a function with ***an internal `[[Construct]]` method*** and a prototype. 
-  line 684
> Since `Rectangle` has ***an internal `[[Construct]]` method*** and a prototype,
- line 756
> there is no ***internal `[[Construct]]` method*** to call.

**Comment by nzakas** [comment]
I did this on purpose. I don't believe it's necessary to repeat "internal" for each instance because the double-bracket notation is indicative of being internal
