### ISSUE TITLE
Potential typo in 11 - Promises - Non-Promise Thenables

### ISSUE THREAD

**Issue by ronen-e** [nzakas/understandinges6#454]
**Where**
Under the section "_Non-Promise Thenables_"

**Problem**
> Both Promise.resolve() and Promise.reject() also accept non-promise thenables as arguments. When passed a non-promise thenable, these methods **create a new promise that is called** after the then() function.

**Reason**
A promise object is not a function therefore it cannot be called. If the use of the term "call" here does not refer to a function call it is still confusing since in other parts of the book the term "call" refers to function calls.

**Solution**
I believe the intent was to say the the new promise is settled after calling the then() function on the thenable object

So perhaps something like this:

> When passed a non-promise thenable, these methods **create a new promise that is settled** after calling the then() method on the thenable object.

This is more in line with ECMAScript standard explanation for the inner workings of a promise object

https://www.ecma-international.org/ecma-262/11.0/index.html#sec-newpromiseresolvethenablejob

<img width="1091" alt="Screen Shot 2020-09-18 at 6 19 37 PM" src="https://user-images.githubusercontent.com/10486251/93615151-b3ec8e00-f9db-11ea-8c8c-f615e682405e.png">

**Comment by nzakas** [comment]
Yeah, your wording makes sense.
