### ISSUE TITLE
Regarding ES6 implementation of super 

### ISSUE THREAD

**Issue by lozandier** [nzakas/understandinges6#55]
Just curious: @nzakas , do you think `super` could have been better implemented in ES6 if it only referred to the method of the super class of the same name as the method it's used in instead of the entire `super`class? 

As @jashkenas noted a year ago in an interesting [feature request] he had to deal with (https://github.com/jashkenas/coffee-script/issues/2638), it seems the current implementation of `super` would enable what some may call an _encapsulation violation_. 
An example of this  I've demonstrated below: 

``` js
class bar extends foo { 
  es6_method(){
   return super.someOtherMethod(1, 2, 3);

  } 
} 
```

**Overall, what's your thoughts on the ES6's  `super` as it is today to allow such behavior potentially with the "final" version of the specification**?

**Comment by Ajedi32** [comment]
@rwaldron Maybe something changed before the standard was finalized, but it seems to me that `super` doesn't work that way. It can only be used as a constructor: http://www.ecma-international.org/ecma-262/6.0/#sec-super-keyword

Babel [agrees](http://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=false&code=class%20Person%20%7B%20%0D%0A%20%20constructor(firstName%2C%20lastName)%20%7B%0D%0A%20%20%20%20this.firstName%20%3D%20firstName%3B%20%0D%0A%20%20%20%20this.lastName%20%3D%20lastName%3B%20%0D%0A%20%20%7D%0D%0A%20%20greet(name)%7B%0D%0A%20%20%20%20return%20%22Hello%2C%20%22%20%2B%20name%3B%20%0D%0A%20%20%7D%0D%0A%20%20get%20fullName()%20%7B%0D%0A%20%20%20%20return%20this.firstName%20%2B%20%22%20%22%20%2B%20this.lastName%3B%20%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20Employee%20extends%20Person%20%7B%20%0D%0A%20%20constructor(firstName%2C%20lastName%2C%20position)%20%7B%0D%0A%20%20%20%20super(firstName%2C%20lastName)%3B%20%0D%0A%20%20%20%20this.position%20%3D%20position%3B%20%0D%0A%20%20%7D%0D%0A%20%20greet(name)%20%7B%0D%0A%20%20%20%20return%20super(name)%20%2B%20%22.%20How%20may%20I%20help%20you%20today%3F%22%3B%20%0D%0A%20%20%7D%0D%0A%20%20get%20fullName()%20%7B%0D%0A%20%20%20%20return%20super.fullName%20%2B%20%22%2C%20%22%20%2B%20this.position%3B%0D%0A%20%20%7D%0D%0A%20%20set%20wage(value)%20%7B%0D%0A%20%20%20%20this._wage%20%3D%20value%3B%20%0D%0A%20%20%7D%0D%0A%20%20get%20wage()%20%7B%0D%0A%20%20%20%20return%20this._wage%3B%20%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Alet%20employee%20%3D%20new%20Employee(%22John%22%2C%20%22Doe%22%2C%20%22Clerk%22)%3B%20%0D%0Aconsole.log(employee.fullName)%3B%20%0D%0A):

> Line 20: Direct super call is illegal in non-constructor, use super."greet"() instead

But it works if you turn on "loose mode", (whatever that is).

**Comment by nzakas** [comment]
Yes, it changed before release. Please note the date of the comment you're referring to.

**Comment by Ajedi32** [comment]
Yep, just wanted to clarify. If I found this thread after all this time chances are others will too, so it's a good idea to set the record straight.
