### ISSUE TITLE
Cover the well-known symbols

### ISSUE THREAD

**Issue by nzakas** [nzakas/understandinges6#59]
- [x] Symbol.hasInstance
- [x] Symbol.isRegExp
- [x] Symbol.toStringTag
- [x] Symbol.iterator
- [x] Symbol.unscopables
- [x] Symbol.toPrimitive
- [x] Symbol.isConcatSpreadable

**Comment by gcnm-pgeil** [comment]
I found the chapter about well-known symbols VERY interesting and helpful in grapsing the actual power and the concepts of Symbols. +1 for covering them!

**Comment by nzakas** [comment]
Done: https://leanpub.com/understandinges6/read#leanpub-auto-well-known-symbols
