### ISSUE TITLE
Combination of default values & destructured parameters

### ISSUE THREAD

**Issue by lgiraudel** [nzakas/understandinges6#97]
It seems possible to use destructured parameters and default values at the same time and I think you should add one example of this kind in the book.

Instead of something like this in ES5:

```
function myFunc(options) {
   options = options || {};
   var params1 = options.params || 'default_value_1';
   var params2 = options.params || 'default_value_2';
   // ...
}
```

it should be possible to use default values & destructured parameters at the same time in ES6:
```
function myFunc({ params1 = 'default_value_1', params2 = 'default_value2' }) {
   // ...
}
```

Here's an example from [here](http://odetocode.com/blogs/scott/archive/2014/09/11/features-of-es6-part-6-destructuring.aspx):

```
let doWork = function({firstName, lastName, role="developer"}) {
    return role + " " + firstName + " " + lastName;
};
 
let person = {firstName: "Scott", lastName: "Allen"};
let result = doWork(person);
 
expect(result).toBe("developer Scott Allen");
```

However I don't know if it's still required to add a default value for the whole object:
```
function myFunc({ params1 = 'default_value_1', params2 = 'default_value2' } = {}) {
   // ...
}
```

**Comment by nzakas** [comment]
Actually added this a while back: https://leanpub.com/understandinges6/read#leanpub-auto-destructured-parameters
