### ISSUE TITLE
Object.assign() - mention similarity to _.extend()?

### ISSUE THREAD

**Issue by bregenspan** [nzakas/understandinges6#99]
Since so many people use Underscore.js and jQuery and they call their `mixin()` methods `extend()`, it might be useful to mention the word "extend" as a synonym of "mixin" in the <a href="https://github.com/nzakas/understandinges6/blob/064151e821b5b5a5eb0ac6eec4fe9c0a393fedb2/manuscript/03-Objects.md#objectassign">Object.assign() discussion</a>.

(I guess mentioning specific libraries might complicate the discussion too much, since although the Underscore one is totally equivalent to Object.assign(), the jQuery one isn't due to supporting deep copy).

**Comment by ORESoftware** [comment]
_.extend was always a misnomer. it should have been _.expand or whatever.

_.extend is for mixins not for inheritance
